import type { Talent } from "./weaponTypes";

export type { Talent, TalentType } from "./weaponTypes";

// ─────────────────────────────────────────────────────────────────────────────
// Gear Talents
// TalentType values used here:
//   "perfectGear"  — Perfect/Perfectly talents on Named backpacks & chests
//   "exoticGear"   — Exclusive talents on Exotic gear pieces
//   "generalGear"  — Standard rollable talents on High-End backpacks & chests
// ─────────────────────────────────────────────────────────────────────────────

export const GEAR_TALENT_LIST: Talent[] = [

  // ── Perfect Backpack Talents ───────────────────────────────────────────────

  {
    talentId:       "perfect-bloodsucker",
    talentName:     "Perfect Bloodsucker",
    talentIcon:     "",
    talentDesc:     "Killing an enemy adds and refreshes a stack of +12% bonus armor for 10s. Max stack is 10.",
    talentType:     "perfectGear",
    upgradedEffect: "+12% bonus armor per stack",
  },
  {
    talentId:       "perfect-overclock",
    talentName:     "Perfect Overclock",
    talentIcon:     "",
    talentDesc:     "You and allies within 15m of your deployed skills gain +30% reload speed and reduces active cooldowns by 0.6 each second.",
    talentType:     "perfectGear",
    upgradedEffect: "15m range, +30% reload speed, 0.6s cooldown reduction/s",
  },
  {
    talentId:       "perfect-creeping-death",
    talentName:     "Perfect Creeping Death",
    talentIcon:     "",
    talentDesc:     "When you apply a status effect, it is also applied to all enemies within 10m of your target. Cooldown: 10s.",
    talentType:     "perfectGear",
    upgradedEffect: "10m radius, 10s cooldown",
  },
  {
    talentId:       "perfectly-unstoppable-force",
    talentName:     "Perfectly Unstoppable Force",
    talentIcon:     "",
    talentDesc:     "Killing an enemy increases total weapon damage by 7% for 15s. Stacks up to 5. Grenade kills add 2 stacks.",
    talentType:     "perfectGear",
    upgradedEffect: "7% per stack, grenade kills add 2 stacks",
  },
  {
    talentId:       "perfectly-wicked",
    talentName:     "Perfectly Wicked",
    talentIcon:     "",
    talentDesc:     "Applying a status effect increases total weapon damage by 18% for 27s.",
    talentType:     "perfectGear",
    upgradedEffect: "27s duration",
  },
  {
    talentId:       "perfect-shock-and-awe",
    talentName:     "Perfect Shock and Awe",
    talentIcon:     "",
    talentDesc:     "Applying a status effect to an enemy increases total skill damage and repair by 20% for 27s.",
    talentType:     "perfectGear",
    upgradedEffect: "27s duration",
  },
  {
    talentId:       "perfect-galvanize",
    talentName:     "Perfect Galvanize",
    talentIcon:     "",
    talentDesc:     "Applying Blind, Ensnare, Confuse, or Shock to an enemy grants 50% of your armor as bonus armor to you and all allies within 30 meters of that enemy for 10 seconds.",
    talentType:     "perfectGear",
    upgradedEffect: "50% armor bonus, 30m radius",
  },
  {
    talentId:       "perfect-adrenaline-rush",
    talentName:     "Perfect Adrenaline Rush",
    talentIcon:     "",
    talentDesc:     "When you are within 10m of an enemy, gain 23% bonus armor for 5s. Stacks up to 3 times. Cooldown: 5s.",
    talentType:     "perfectGear",
    upgradedEffect: "23% bonus armor per stack",
  },
  {
    talentId:       "perfect-vigilance",
    talentName:     "Perfect Vigilance",
    talentIcon:     "",
    talentDesc:     "Increases total weapon damage by 25%. Taking damage disables buff for 3s.",
    talentType:     "perfectGear",
    upgradedEffect: "3s disable duration",
  },
  {
    talentId:       "perfect-tech-support",
    talentName:     "Perfect Tech Support",
    talentIcon:     "",
    talentDesc:     "Skill kills increase total skill damage by 25% for 27s.",
    talentType:     "perfectGear",
    upgradedEffect: "27s duration",
  },
  {
    talentId:       "perfect-versatile",
    talentName:     "Perfect Versatile",
    talentIcon:     "",
    talentDesc:     "Amplifies total weapon damage for 10s when swapping between your primary and secondary weapons if they are different. 45% to enemies within 15m for Shotguns and SMGs. 45% to enemies further than 25m for Rifles and MMRs. 20% to enemies between 15-25m for LMGs and ARs. At most once per 5s per weapon type.",
    talentType:     "perfectGear",
    upgradedEffect: "45%/45%/20% amplification",
  },
  {
    talentId:       "perfect-clutch",
    talentName:     "Perfect Clutch",
    talentIcon:     "",
    talentDesc:     "When you are below 20% armor, critical hits repair 2.5% of missing armour. On kill, critical hits repair 2.5% of missing armour. Lowest possible repair is 0% armour. Each red core attribute adds 1 second to the time. Maximum is 10 seconds.",
    talentType:     "perfectGear",
    upgradedEffect: "20% armor threshold",
  },
  {
    talentId:       "perfectly-calculated",
    talentName:     "Perfectly Calculated",
    talentIcon:     "",
    talentDesc:     "Kills from cover reduce skill cooldowns by 15%.",
    talentType:     "perfectGear",
    upgradedEffect: "15% cooldown reduction",
  },
  {
    talentId:       "perfectly-opportunistic",
    talentName:     "Perfectly Opportunistic",
    talentIcon:     "",
    talentDesc:     "Enemies you hit with shotguns and marksman rifles amplifies the damage they take by 15% from all sources for 5s.",
    talentType:     "perfectGear",
    upgradedEffect: "15% amplified damage",
  },
  {
    talentId:       "perfect-combined-arms",
    talentName:     "Perfect Combined Arms",
    talentIcon:     "",
    talentDesc:     "Shooting an enemy increases total skill damage by 30% for 3s.",
    talentType:     "perfectGear",
    upgradedEffect: "30% total skill damage",
  },
  {
    talentId:       "perfectly-tamper-proof",
    talentName:     "Perfectly Tamper Proof",
    talentIcon:     "",
    talentDesc:     "Enemies that walk within 3 meters of your hive, turret, remote pulse, or decoy are shocked. Arm time: 2 seconds. Cooldown per Skill: 8 seconds.",
    talentType:     "perfectGear",
  },
  {
    talentId:       "perfect-energize",
    talentName:     "Perfect Energize",
    talentIcon:     "",
    talentDesc:     "Using an armor kit grants +1 Skill Tier for 15s. If already at Skill Tier 6, grants Overcharge. Cooldown: 30s.",
    talentType:     "perfectGear",
    upgradedEffect: "Cooldown: 30s",
  },
  {
    talentId:       "perfect-leadership",
    talentName:     "Perfect Leadership",
    talentIcon:     "",
    talentDesc:     "Performing a cover to cover grants 20% of your armor as bonus armor to you and all allies for 10s. This is Tripled if you end within 10m of an enemy. Cooldown: 10s.",
    talentType:     "perfectGear",
    upgradedEffect: "20% armor bonus, tripled if within 10m of enemy",
  },
  {
    talentId:       "fireworks-show",
    talentName:     "Fireworks Show",
    talentIcon:     "",
    talentDesc:     "Concussion grenades become Festive Grenades. Hitting an enemy with a Festive Grenade will cause explosions to happen around two other enemies within 20m, 10m in PvP. *Dealing 15% damage in PvP.",
    talentType:     "perfectGear",
  },

  // ── Perfect Chest Talents ──────────────────────────────────────────────────

  {
    talentId:       "perfect-companion",
    talentName:     "Perfect Companion",
    talentIcon:     "",
    talentDesc:     "While you are within 10m of an ally or skill, total weapon damage is increased by 20%.",
    talentType:     "perfectGear",
    upgradedEffect: "10m range, 20% weapon damage",
  },
  {
    talentId:       "perfect-intimidate",
    talentName:     "Perfect Intimidate",
    talentIcon:     "",
    talentDesc:     "While you have bonus armour, gain 3 stacks each second up to a max of 10. Each stack increases total weapon damage by 4% to enemies within 10m. All stacks are lost when you have no bonus armour.",
    talentType:     "perfectGear",
    upgradedEffect: "10 stacks max",
  },
  {
    talentId:       "perfectly-efficient",
    talentName:     "Perfectly Efficient",
    talentIcon:     "",
    talentDesc:     "Using an armor kit has a 75% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 100%. Requires 10 seconds to arm talent.",
    talentType:     "perfectGear",
    upgradedEffect: "75% chance to not consume",
  },
  {
    talentId:       "perfect-headhunter",
    talentName:     "Perfect Headhunter",
    talentIcon:     "",
    talentDesc:     "After killing an enemy with a headshot, your next weapon hit within 30s deals 150% of that killing blow's damage in addition to it. Damage is capped to 800% of your weapon damage. This is raised to 1250% if your headshot damage is greater than 150%.",
    talentType:     "perfectGear",
    upgradedEffect: "150% of killing blow's damage",
  },
  {
    talentId:       "perfect-vanguard",
    talentName:     "Perfect Vanguard",
    talentIcon:     "",
    talentDesc:     "Deploying a shield makes it invulnerable for 5s and grants 50% of your armor as bonus armor to all other allies for 20s. Cooldown: 25s.",
    talentType:     "perfectGear",
    upgradedEffect: "50% armor as bonus armor to allies",
  },
  {
    talentId:       "perfect-braced",
    talentName:     "Perfect Braced",
    talentIcon:     "",
    talentDesc:     "While in cover weapon handling is increased by +50%.",
    talentType:     "perfectGear",
    upgradedEffect: "+50% weapon handling",
  },
  {
    talentId:       "perfect-glass-cannon",
    talentName:     "Perfect Glass Cannon",
    talentIcon:     "",
    talentDesc:     "All damage you deal is amplified by 30%. All damage you take is amplified by 60%.",
    talentType:     "perfectGear",
    upgradedEffect: "30% damage dealt, 60% damage taken",
  },
  {
    talentId:       "perfect-unbreakable",
    talentName:     "Perfect Unbreakable",
    talentIcon:     "",
    talentDesc:     "When your armor is depleted, repair 100% of your armor. Cooldown: 55s.",
    talentType:     "perfectGear",
    upgradedEffect: "100% armor repair",
  },
  {
    talentId:       "perfect-overwatch",
    talentName:     "Perfect Overwatch",
    talentIcon:     "",
    talentDesc:     "After staying in cover for 8 seconds, increase your and all allies' total weapon and skill damage by 14% as long as you remain in cover, or in a cover to cover move.",
    talentType:     "perfectGear",
    upgradedEffect: "8s to activate, 14% weapon and skill damage",
  },
  {
    talentId:       "perfect-spark",
    talentName:     "Perfect Spark",
    talentIcon:     "",
    talentDesc:     "Damaging an enemy with a skill increases total weapon damage by 18% for 20 seconds.",
    talentType:     "perfectGear",
    upgradedEffect: "18% weapon damage, 20s duration",
  },
  {
    talentId:       "perfectly-skilled",
    talentName:     "Perfectly Skilled",
    talentIcon:     "",
    talentDesc:     "Skill kills have a 30% chance to reset skill cooldowns.",
    talentType:     "perfectGear",
    upgradedEffect: "30% chance to reset",
  },
  {
    talentId:       "perfect-spotter",
    talentName:     "Perfect Spotter",
    talentIcon:     "",
    talentDesc:     "Amplifies total weapon and skill damage by 20% to pulsed enemies.",
    talentType:     "perfectGear",
    upgradedEffect: "20% weapon and skill damage amplification",
  },
  {
    talentId:       "perfect-trauma",
    talentName:     "Perfect Trauma",
    talentIcon:     "",
    talentDesc:     "Applies blind to enemy hit in the head. Cooldown 20 seconds. Applies bleed to an enemy hit in the chest. Cooldown 20 seconds.",
    talentType:     "perfectGear",
    upgradedEffect: "20s cooldown",
  },
  {
    talentId:       "perfectly-mad-bomber",
    talentName:     "Perfectly Mad Bomber",
    talentIcon:     "",
    talentDesc:     "Grenade Radius is increased by 75%. Grenades that kill an enemy are refunded. Grenades can now be \"cooked\" by holding the fire button, making them explode earlier. Gain 15% bonus armor while aiming grenades.",
    talentType:     "perfectGear",
    upgradedEffect: "75% grenade radius",
  },
  {
    talentId:       "perfect-entrench",
    talentName:     "Perfect Entrench",
    talentIcon:     "",
    talentDesc:     "If you are below 30% Armor, headshots from cover repair 30% of your armor. Cooldown 2 seconds.",
    talentType:     "perfectGear",
    upgradedEffect: "30% armor repair from headshots",
  },
  {
    talentId:       "perfect-focus",
    talentName:     "Perfect Focus",
    talentIcon:     "",
    talentDesc:     "Increases total weapon damage by 6% every second you are aiming while scoped 8x or higher, up to 60%.",
    talentType:     "perfectGear",
    upgradedEffect: "6%/s up to 60% weapon damage",
  },
  {
    talentId:       "perfect-protected-reload",
    talentName:     "Perfect Protected Reload",
    talentIcon:     "",
    talentDesc:     "Grants +40% bonus armor while reloading. Grants 0-30% of your armor as bonus armor to all other allies when they are reloading, based on your Blue core attribute.",
    talentType:     "perfectGear",
    upgradedEffect: "+40% bonus armor while reloading, up to 30% for allies",
  },
  {
    talentId:       "perfectly-explosive-delivery",
    talentName:     "Perfectly Explosive Delivery",
    talentIcon:     "",
    talentDesc:     "Whenever you throw a skill, 1.5 seconds after landing, it creates an explosion damaging enemies within 5m. Afterwards explosions will occur every 5s. Damage scales with skill tier dealing 25-100% damage of a concussion grenade. Occurs once per skill. Applies to Remote Pulse, All Turrets, All Hives, Explosive Seeker, Cluster Seeker, Mender Seeker, Decoy, All Traps.",
    talentType:     "perfectGear",
  },
  {
    talentId:       "perfect-obliterate",
    talentName:     "Perfect Obliterate",
    talentIcon:     "",
    talentDesc:     "Critical hits increase total weapon damage by 1% for 10s. Stacks up to 24 times.",
    talentType:     "perfectGear",
    upgradedEffect: "24 stacks max",
  },

  // ── Special Event / Unique Kneepad Talents ─────────────────────────────────

  {
    talentId:   "flurry",
    talentName: "Flurry",
    talentIcon: "",
    talentDesc: "Status effects apply snowfall to target.",
    talentType: "perfectGear",
  },
  {
    talentId:   "bewildered",
    talentName: "Bewildered",
    talentIcon: "",
    talentDesc: "When dealing Weapon Damage to an enemy, 50% of the damage will be dealt to another enemy within 30m instead. When there are no enemies nearby, deal damage normally. Does not apply to Armor Plates.",
    talentType: "perfectGear",
  },

  // ── Exotic Mask Talents ────────────────────────────────────────────────────

  {
    talentId:   "toxic-delivery",
    talentName: "Toxic Delivery",
    talentIcon: "",
    talentDesc: "Status effects also apply a damage over time debuff for 10s. Total Damage dealt is equal to 50% of your concussion grenade damage and increased by your status effect attributes.",
    talentType: "exoticGear",
  },
  {
    talentId:   "vicious-cycle",
    talentName: "Vicious Cycle",
    talentIcon: "",
    talentDesc: "Taking damage builds stacks to a cap of 30. Each stack grants 1.5% Weapon Damage. Total Damage at max stacks triggers a purge, removing all stacks and Status Effects and then dropping a healing cloud which restores 5% of Max Armor for 10s to all allies in the cloud.",
    talentType: "exoticGear",
  },
  {
    talentId:   "pack-instincts",
    talentName: "Pack Instincts",
    talentIcon: "",
    talentDesc: "You and all allies gain a bonus based on the distance of the last enemy you hit. 0-15m: +25% critical hit damage. 15-25m: +10% critical hit chance and +10% critical hit damage. 25m+: +25% critical hit Chance.",
    talentType: "exoticGear",
  },
  {
    talentId:   "chemical-agent",
    talentName: "Chemical Agent",
    talentIcon: "",
    talentDesc: "Catalysis: Dealing and receiving status effects builds stacks to a maximum of 12. Each stack grants +2% Weapon Damage and +2% Status Effects. Each enemy within 25m affected by a status effect grants +1 stack/sec; being affected yourself grants +2 stacks/sec. Stacks decay at 1/sec after 5s if no enemies are in radius or you are affected by status effects. | Reactant: At max stacks, killing a status-affected enemy grants for 5s: +25% bonus armor, +20% reload speed. | Stabilizer: While burning, you can maintain ADS without disruption.",
    talentType: "exoticGear",
  },
  {
    talentId:   "abridged",
    talentName: "Abridged",
    talentIcon: "",
    talentDesc: "If your Primary and Secondary weapon are not Exotic or Named and of the same type, the Secondary Weapon's talent will also be applied to the Primary Weapon. Doesn't apply to talents that include Weapon Swapping.",
    talentType: "exoticGear",
  },

  // ── Exotic Backpack Talents ────────────────────────────────────────────────

  {
    talentId:   "one-in-the-hand",
    talentName: "One in the Hand... / ...Two in the Bag",
    talentIcon: "",
    talentDesc: "One in the Hand...: Throwing a grenade refunds it and grants +1 Skill Tier for 15s. Grants Overcharge if already at Skill Tier 6. Cooldown: 60s. | ...Two in the Bag: +1 Armor Kit Capacity, +3 Grenade Capacity, +25% Ammo Capacity, +10% Repair Skills, +10% Status Effects.",
    talentType: "exoticGear",
  },
  {
    talentId:   "combat-medic",
    talentName: "Combat Medic",
    talentIcon: "",
    talentDesc: "+80% Revive Speed, -50% Weakened Debuff timer, +45% Hive efficiency. Provides +50% damage resistance to both agents while reviving or being revived, and for 5s after a successful Hive Revive, or 10s after a Manual Revive. Any successful revives provide +1 Skill Tier for 5s. Revives at Skill Tier 6 grant Overcharge for 15s.",
    talentType: "exoticGear",
  },
  {
    talentId:   "kill-confirmed",
    talentName: "Kill Confirmed",
    talentIcon: "",
    talentDesc: "Enemies you kill drop a trophy on death. Collecting trophies provides both a short and long term buff, the first of which scales with the number of core attributes equipped and lasts 10s. Red Core: -5% Weapon Damage. Blue Core: -10% Bonus Armor. Yellow Core: -5% Skill Efficiency. For every trophy collected gain an additional +1% weapon damage, +1% skill efficiency and +0.1% armor regeneration for 300s. Maximum 30 stacks.",
    talentType: "exoticGear",
  },
  {
    talentId:   "resourceful",
    talentName: "Resourceful",
    talentIcon: "",
    talentDesc: "Slots in with any equipped Gear Set and/or Brand Set item to fulfill a requirement towards unlocking a Gear and/or Brand Sets bonus. Can unlock bonuses from multiple sets simultaneously.",
    talentType: "exoticGear",
  },
  {
    talentId:   "rebalance",
    talentName: "Rebalance",
    talentIcon: "",
    talentDesc: "Getting kills and hitting enemies 3 times builds Red stacks. Each stack provides 0.5% Weapon Damage. Getting hit 3 times builds Blue stacks. Each stack provides 0.5% Damage Resistance. Upon reaching 80 stacks in total, lose all stacks and receive a separate bonus of 0.5% Damage Resistance per Red stack and 0.5% Weapon Damage per Blue stack until the next time the stack cap is reached.",
    talentType: "exoticGear",
  },

  // ── Exotic Glove Talents ───────────────────────────────────────────────────

  {
    talentId:   "over-the-top",
    talentName: "Over the Top",
    talentIcon: "",
    talentDesc: "Red. Seeing Red grants +25% weapon damage and +100% melee damage. Seeing Red lasts 20 seconds and starts a 60 second cooldown after completion. While in cooldown, damaging an enemy with a melee attack or hitting an enemy with the effect of a grenade will complete the cooldown instantly. (Note: the 25% 'weapon damage' buff actually gives total weapon damage.)",
    talentType: "exoticGear",
  },
  {
    talentId:   "transference-overclock",
    talentName: "Transference Overclock",
    talentIcon: "",
    talentDesc: "Grants 15% Hive skill haste per skill tier. Detonating a hive refreshes your skill cooldowns and grants overcharge for 15s. If at Skill Tier 6, this effect also applies to all allies. Allies receiving this effect are unable to benefit from it again for 120s.",
    talentType: "exoticGear",
  },
  {
    talentId:   "smoke-screen",
    talentName: "Smoke Screen",
    talentIcon: "",
    talentDesc: "On Armor break, drop a Smoke Bomb at your feet, concealing you from enemies for 3s. Cooldown: 40s.",
    talentType: "exoticGear",
  },
  {
    talentId:   "weakest-link",
    talentName: "Weakest Link",
    talentIcon: "",
    talentDesc: "Amplifies Weapon Damage by 30% to the lowest ranking enemies currently in combat, as per the Tier hierarchy. Tier 1: Hunter, Rogue, Leader, Tank, Shield, Heavy Weapons, RPG, Medic, Controller, Warhound, Marauder. Tier 2: Support, Engineer, Bodyguard, Immobilizer, Bomber, Mini Tank, Drone Operator. Tier 3: Any other enemy or skill proxy. (Tier 3 is lowest, Tier 1 is highest.)",
    talentType: "exoticGear",
  },
  {
    talentId:   "iron-grip",
    talentName: "Iron Grip",
    talentIcon: "",
    talentDesc: "-50% Recoil Penalty when hip-firing. -50% Recoil Penalty when blind-firing from cover.",
    talentType: "exoticGear",
  },

  // ── Exotic Holster Talents ─────────────────────────────────────────────────

  {
    talentId:   "counter",
    talentName: "Counter",
    talentIcon: "",
    talentDesc: "Swapping weapons will give the following groups of bonuses one by one, in order: 1. +20% Rate of Fire, +20% Weapon Damage. 2. +50% Magazine Size, +50% Reload Speed. The bonuses remain active for 12s or until the next weapon swap. Swapping to your sidearm will not trigger the next group of bonuses.",
    talentType: "exoticGear",
  },
  {
    talentId:   "quick-draw",
    talentName: "Quick Draw",
    talentIcon: "",
    talentDesc: "While your pistol is holstered, gain a stacking buff every 0.3s, up to 100. When you swap to it, your first shot consumes the buff and deals +10% damage per stack. This deals headshot damage to anywhere you hit. Requires Pistol Equipped.",
    talentType: "exoticGear",
  },
  {
    talentId:   "dragons-glare",
    talentName: "Dragon's Glare",
    talentIcon: "",
    talentDesc: "While in combat, applies burn to the enemy closest to you within 20m. Cooldown: 35s.",
    talentType: "exoticGear",
  },
  {
    talentId:   "defibrillator",
    talentName: "Defibrillator",
    talentIcon: "",
    talentDesc: "While Shocker Punch is equipped, the stun received from the Shock status effect is reduced by 50%. Using a shield gives 100% bonus melee damage. Using St. Elmo's Engine with this holster gives 100% extra melee damage and makes the next melee attack apply shock to the target. Using all three items provides all bonuses and the Shock from melee attacks has a 5m radius from the first target. 15 second cooldown.",
    talentType: "exoticGear",
  },
  {
    talentId:   "alternating-current",
    talentName: "Alternating Current",
    talentIcon: "",
    talentDesc: "Generate a stack of 3% skill damage on one of your skills every second, capping at 10 stacks. After 10 seconds at the cap the stacks transfer to your other skill. The process then repeats ad-infinitum.",
    talentType: "exoticGear",
  },
  {
    talentId:   "bob-and-weave",
    talentName: "Bob and Weave",
    talentIcon: "",
    talentDesc: "Receive repairs of 5% of your Total Armor for every 1m run in cover-to-cover. Damage taken while doing a cover-to-cover is healed over 10s.",
    talentType: "exoticGear",
  },

  // ── Exotic Chest Talents ───────────────────────────────────────────────────

  {
    talentId:   "hoarder",
    talentName: "Hoarder",
    talentIcon: "",
    talentDesc: "+3 Grenade Capacity, +50% Grenade Radius, +35% Grenade Damage, +25% Grenade Damage for each extra enemy caught in the blast. Automatically regenerate grenades every 30s if you have less than 2 grenades in your inventory.",
    talentType: "exoticGear",
  },
  {
    talentId:   "challenger",
    talentName: "Challenger",
    talentIcon: "",
    talentDesc: "Receive +25% Damage resistance from enemies within 20m.",
    talentType: "exoticGear",
  },
  {
    talentId:   "bond",
    talentName: "Bond",
    talentIcon: "",
    talentDesc: "Both you and Allies receive +30% Critical Hit Damage, +15% Skill Efficiency and +2% Armor Regen when an Ally is within 10m of you. Receive +15% Critical Hit Damage, +7.5% Skill Efficiency and +1% Armor Regen when one of your Skills is within 10m of you. Only the highest group of buffs can be active at one time.",
    talentType: "exoticGear",
  },
  {
    talentId:   "ablative-nano-plating",
    talentName: "Ablative Nano-Plating",
    talentIcon: "",
    talentDesc: "Whenever you or any ally's armor breaks, they gain 80% of your armor as bonus armor for 10s. Cooldown per ally: 45s. Killing an enemy with your specialization weapon removes this cooldown for all allies.",
    talentType: "exoticGear",
  },
  {
    talentId:   "bleeding-edge",
    talentName: "Bleeding Edge",
    talentIcon: "",
    talentDesc: "Shooting enemies within 15m applies bleed to the target. Repair 3-48% of your armor per second for every enemy that is bleeding within 15m. Repair strength per number of bleeding enemies — 1:3% 2:6% 3:12% 4:24% 5:48%.",
    talentType: "exoticGear",
  },

  // ── Exotic Kneepad Talents ─────────────────────────────────────────────────

  {
    talentId:   "stand-your-ground",
    talentName: "Stand Your Ground",
    talentIcon: "",
    talentDesc: "Cannot be staggered by explosions. Increases total weapon damage by 3% each second you are not moving. Stacks up to 10 until you start moving. All stacks lost 10s after moving.",
    talentType: "exoticGear",
  },
  {
    talentId:   "escape-plan",
    talentName: "Escape Plan",
    talentIcon: "",
    talentDesc: "Vaulting grants +10% Movement Speed for 3s. After not moving for 5s, receive +20% Movement Speed for 5s. Being applied a Status Effect grants +10% Movement Speed for 5s. Max Movement Speed bonus is 20%. The bonuses do not stack with Movement Speed bonuses from other sources. -50% Movement Impairment penalty from Status Effects.",
    talentType: "exoticGear",
  },
  {
    talentId:   "ostracize",
    talentName: "Ostracize",
    talentIcon: "",
    talentDesc: "Shooting an enemy applies a mark. Only one mark can be active at a time. The mark disappears after 15s, or when the marked enemy dies. Receive 600% Amplified Damage from the marked enemy. Deal 20% Amplified Damage to unmarked enemies. If only one enemy remains in combat, the mark disappears and cannot be reapplied.",
    talentType: "exoticGear",
  },
  {
    talentId:   "parkour",
    talentName: "Parkour!",
    talentIcon: "",
    talentDesc: "Performing a cover to cover or vaulting reloads your drawn weapon and grants +25% bonus armor for 5s.",
    talentType: "exoticGear",
  },

  // ── General Gear Talents (rollable on High-End chest & backpack) ───────────

  {
    talentId:   "combined-arms",
    talentName: "Combined Arms",
    talentIcon: "",
    talentDesc: "Shooting an enemy increases total skill damage by 25% for 3s.",
    talentType: "generalGear",
  },
  {
    talentId:   "tech-support",
    talentName: "Tech Support",
    talentIcon: "",
    talentDesc: "Skill kills increase total skill damage by 25% for 25s.",
    talentType: "generalGear",
  },
  {
    talentId:   "shock-and-awe",
    talentName: "Shock and Awe",
    talentIcon: "",
    talentDesc: "Applying a status effect to an enemy increases total skill damage and repair by 20% for 20s.",
    talentType: "generalGear",
  },
  {
    talentId:   "vigilance",
    talentName: "Vigilance",
    talentIcon: "",
    talentDesc: "Increases total weapon damage by 25%. Taking damage disables this buff for 4s.",
    talentType: "generalGear",
  },
  {
    talentId:   "versatile",
    talentName: "Versatile",
    talentIcon: "",
    talentDesc: "Amplifies total weapon damage for 10s when swapping between your primary and secondary weapons if they are different. 35% to enemies within 15m for Shotguns and SMGs. 35% to enemies further than 25m for Rifles and MMRs. 10% to enemies between 15-25m for LMGs and ARs. At most once per 5s per weapon type.",
    talentType: "generalGear",
  },
  {
    talentId:   "unstoppable-force",
    talentName: "Unstoppable Force",
    talentIcon: "",
    talentDesc: "Killing an enemy increases total weapon damage by 5% for 15s. Stacks up to 5 times.",
    talentType: "generalGear",
  },
  {
    talentId:   "companion",
    talentName: "Companion",
    talentIcon: "",
    talentDesc: "While you are within 5m of an ally or skill, total weapon damage is increased by 15%.",
    talentType: "generalGear",
  },
  {
    talentId:   "composure",
    talentName: "Composure",
    talentIcon: "",
    talentDesc: "While in cover, increases total weapon damage by 15%.",
    talentType: "generalGear",
  },
  {
    talentId:   "concussion",
    talentName: "Concussion",
    talentIcon: "",
    talentDesc: "Headshots increase total weapon damage by 10% for 1.5s. 5s with marksman rifles. Headshot kills increase total weapon damage by 15% for 10s. Both buffs can be active for an increase of 25% total weapon damage.",
    talentType: "generalGear",
  },
  {
    talentId:   "wicked",
    talentName: "Wicked",
    talentIcon: "",
    talentDesc: "Applying a status effect increases total weapon damage by 18% for 20s.",
    talentType: "generalGear",
  },
  {
    talentId:   "opportunistic",
    talentName: "Opportunistic",
    talentIcon: "",
    talentDesc: "Enemies you hit with shotguns and marksman rifles amplifies the damage they take by 10% from all sources for 5s.",
    talentType: "generalGear",
  },
  {
    talentId:   "clutch",
    talentName: "Clutch",
    talentIcon: "",
    talentDesc: "When you are below 15% armor, critical hits repair 2.5% of missing armor. On kill, critical hits repair 2.5% of missing armor for 4 seconds. Lowest possible repair is 0% armour. Each red core attribute adds 1 second to the time. Maximum is 10 seconds.",
    talentType: "generalGear",
  },
  {
    talentId:   "safeguard",
    talentName: "Safeguard",
    talentIcon: "",
    talentDesc: "While at full armor, increases total skill repair by 130%.",
    talentType: "generalGear",
  },
  {
    talentId:   "bloodsucker",
    talentName: "Bloodsucker",
    talentIcon: "",
    talentDesc: "Killing an enemy adds and refreshes a stack of +10% bonus armor for 10s. Max stack is 10.",
    talentType: "generalGear",
  },
  {
    talentId:   "leadership",
    talentName: "Leadership",
    talentIcon: "",
    talentDesc: "Performing a cover to cover grants 15% of your armor as bonus armor to you and all allies for 10s. This is doubled if you end within 10m of an enemy. Cooldown: 10s.",
    talentType: "generalGear",
  },
  {
    talentId:   "protector",
    talentName: "Protector",
    talentIcon: "",
    talentDesc: "When your shield is damaged, you gain +5% and all other allies gain +15% of your armor as bonus armor for 3s. Cooldown: 3s.",
    talentType: "generalGear",
  },
  {
    talentId:   "adrenaline-rush",
    talentName: "Adrenaline Rush",
    talentIcon: "",
    talentDesc: "When you are within 10m of an enemy, gain 20% bonus armor for 5s. Stacks up to 3 times. Cooldown: 5s.",
    talentType: "generalGear",
  },
  {
    talentId:   "galvanize",
    talentName: "Galvanize",
    talentIcon: "",
    talentDesc: "Applying a Blind, Ensnare, Confuse, or Shock to an enemy grants 40% of your armor as bonus armor to you and all allies within 20m of that enemy for 10s.",
    talentType: "generalGear",
  },
  {
    talentId:   "energize",
    talentName: "Energize",
    talentIcon: "",
    talentDesc: "Using an armor kit grants +1 skill tier for 15s. If already at skill tier 6, grants overcharge. Cooldown: 60s.",
    talentType: "generalGear",
  },
  {
    talentId:   "calculated",
    talentName: "Calculated",
    talentIcon: "",
    talentDesc: "Kills from cover reduce skill cooldowns by 10%.",
    talentType: "generalGear",
  },
  {
    talentId:   "overclock",
    talentName: "Overclock",
    talentIcon: "",
    talentDesc: "You and allies within 7m of your deployed skills gain +25% reload speed and reduces active cooldowns by 0.2 each second.",
    talentType: "generalGear",
  },
  {
    talentId:   "creeping-death",
    talentName: "Creeping Death",
    talentIcon: "",
    talentDesc: "When you apply a status effect, it is also applied to all enemies within 8m of your target. Cooldown: 15s.",
    talentType: "generalGear",
  },
  {
    talentId:   "explosive-delivery",
    talentName: "Explosive Delivery",
    talentIcon: "",
    talentDesc: "Whenever you throw a skill, 1.5 seconds after landing, it creates an explosion damaging enemies within 5m. Afterwards explosions will occur every 5s. Damage scales with skill tier dealing 25-100% damage of a concussion grenade. Occurs once per skill. Applies to Remote Pulse, All Turrets, All Hives, Explosive Seeker, Cluster Seeker, Mender Seeker, Decoy, All Traps.",
    talentType: "generalGear",
  },
  {
    talentId:   "kinetic-momentum",
    talentName: "Kinetic Momentum",
    talentIcon: "",
    talentDesc: "When in combat, each skill generates stacks while active or not on cooldown. Each stack increases your total skill damage by 1.5% and total skill repair by 2%. Up to 15 stacks per skill. Stacks are lost when skills go on cooldown.",
    talentType: "generalGear",
  },
  {
    talentId:   "gunslinger",
    talentName: "Gunslinger",
    talentIcon: "",
    talentDesc: "Weapon swapping increases total weapon damage by 23% for 5s. This buff is lost for 5s if you weapon swap while it is active.",
    talentType: "generalGear",
  },
  {
    talentId:   "focus",
    talentName: "Focus",
    talentIcon: "",
    talentDesc: "Increases total weapon damage by 5% every second you are aiming while scoped 8x or higher, up to 50%.",
    talentType: "generalGear",
  },
  {
    talentId:   "spark",
    talentName: "Spark",
    talentIcon: "",
    talentDesc: "Damaging an enemy with a skill increases total weapon damage by 15% for 15s.",
    talentType: "generalGear",
  },
  {
    talentId:   "obliterate",
    talentName: "Obliterate",
    talentIcon: "",
    talentDesc: "Critical hits increase total weapon damage by 1% for 10s. Stacks up to 20 times.",
    talentType: "generalGear",
  },
  {
    talentId:   "intimidate",
    talentName: "Intimidate",
    talentIcon: "",
    talentDesc: "While you have bonus armour, gain 3 stacks each second up to a max of 9. Each stack increases total weapon damage by 4% to enemies within 10m. All stacks are lost when you have no bonus armour.",
    talentType: "generalGear",
  },
  {
    talentId:   "headhunter",
    talentName: "Headhunter",
    talentIcon: "",
    talentDesc: "After killing an enemy with a headshot, your next weapon hit within 30s deals 125% of that killing blow's damage in addition to it. Damage is capped to 800% of your weapon damage. This is raised to 1250% if your headshot damage is greater than 150%.",
    talentType: "generalGear",
  },
  {
    talentId:   "empathic-resolve",
    talentName: "Empathic Resolve",
    talentIcon: "",
    talentDesc: "Repairing an ally increases their total weapon and skill damage by 3-15% for 10s, or 1-7% if self. Effectiveness increased by your skill tier.",
    talentType: "generalGear",
  },
  {
    talentId:   "overwatch",
    talentName: "Overwatch",
    talentIcon: "",
    talentDesc: "After staying in cover for 10s, increase your and all allies' total weapon and skill damage by 12% as long as you remain in cover or in a cover-to-cover move.",
    talentType: "generalGear",
  },
  {
    talentId:   "glass-cannon",
    talentName: "Glass Cannon",
    talentIcon: "",
    talentDesc: "All damage you deal is amplified by 25%. All damage you take is amplified by 50%.",
    talentType: "generalGear",
  },
  {
    talentId:   "spotter",
    talentName: "Spotter",
    talentIcon: "",
    talentDesc: "Amplifies total weapon and skill damage by 15% to pulsed enemies.",
    talentType: "generalGear",
  },
  {
    talentId:   "unbreakable",
    talentName: "Unbreakable",
    talentIcon: "",
    talentDesc: "When your armor is depleted, repair 95% of your armor. Cooldown: 60s.",
    talentType: "generalGear",
  },
  {
    talentId:   "vanguard",
    talentName: "Vanguard",
    talentIcon: "",
    talentDesc: "Deploying a shield makes it invulnerable for 5s and grants 45% of your armor as bonus armor to all other allies for 20s. Cooldown: 25s.",
    talentType: "generalGear",
  },
  {
    talentId:   "protected-reload",
    talentName: "Protected Reload",
    talentIcon: "",
    talentDesc: "Grants +20% bonus armor while reloading. Grants 0%-18% of your armor as bonus armor to all other allies when they are reloading. Each blue core attribute adds 3% to the bonus armour.",
    talentType: "generalGear",
  },
  {
    talentId:   "entrench",
    talentName: "Entrench",
    talentIcon: "",
    talentDesc: "If you are below 30% armor, headshots from cover repair 20% of your armor. Cooldown: 2 seconds.",
    talentType: "generalGear",
  },
  {
    talentId:   "efficient",
    talentName: "Efficient",
    talentIcon: "",
    talentDesc: "Using an armor kit has a 50% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 100%. Requires 10 seconds to arm talent.",
    talentType: "generalGear",
  },
  {
    talentId:   "mad-bomber",
    talentName: "Mad Bomber",
    talentIcon: "",
    talentDesc: "Grenade Radius is increased by 50%. Grenades that kill an enemy are refunded. Grenades can now be \"cooked\" by holding the fire button, making them explode earlier. Gain 15% bonus armor while aiming grenades.",
    talentType: "generalGear",
  },
  {
    talentId:   "braced",
    talentName: "Braced",
    talentIcon: "",
    talentDesc: "While in cover weapon handling is increased by 45%.",
    talentType: "generalGear",
  },
  {
    talentId:   "skilled",
    talentName: "Skilled",
    talentIcon: "",
    talentDesc: "Skill kills have a 25% chance to reset skill cooldowns.",
    talentType: "generalGear",
  },
  {
    talentId:   "tag-team",
    talentName: "Tag Team",
    talentIcon: "",
    talentDesc: "The last enemy you have damaged with a skill is marked. Dealing weapon damage to that enemy consumes the mark to reduce active cooldowns by 6s. Cooldown: 4s.",
    talentType: "generalGear",
  },
  {
    talentId:   "trauma",
    talentName: "Trauma",
    talentIcon: "",
    talentDesc: "Applies blind to an enemy hit in the head. Cooldown: 30 seconds. Applies bleed to an enemy hit in the chest. Cooldown: 30 seconds.",
    talentType: "generalGear",
  },
  {
    talentId:   "tamper-proof",
    talentName: "Tamper Proof",
    talentIcon: "",
    talentDesc: "Enemies that walk within 3 meters of your hive, turret, remote pulse, or decoy are shocked. Arm time: 2 seconds. Cooldown per skill: 10 seconds.",
    talentType: "generalGear",
  },
  {
    talentId:   "reassigned",
    talentName: "Reassigned",
    talentIcon: "",
    talentDesc: "Killing an enemy adds 1 round of a random special ammo into your sidearm. Cooldown: 15 seconds.",
    talentType: "generalGear",
  },

];

// ─────────────────────────────────────────────────────────────────────────────
// Derived helpers
// ─────────────────────────────────────────────────────────────────────────────

export const GEAR_TALENT_MAP = new Map(GEAR_TALENT_LIST.map(t => [t.talentId, t]));
