import type { WeaponType } from "./weaponTypes";

export interface HighEndWeapon {
  weaponId:   string;
  weaponName: string;
  baseModel:  string;
  type:       WeaponType;
}

export const HIGH_END_WEAPONS: HighEndWeapon[] = [

  // ── Assault Rifles ────────────────────────────────────────────────────────
  { weaponId: "acr",                              weaponName: "ACR",                              baseModel: "ACR",         type: "Assault Rifle" },
  { weaponId: "acr-e",                            weaponName: "ACR-E",                            baseModel: "ACR",         type: "Assault Rifle" },
  { weaponId: "ak-m",                             weaponName: "AK-M",                             baseModel: "AK-47",       type: "Assault Rifle" },
  { weaponId: "military-ak-m",                    weaponName: "Military AK-M",                    baseModel: "AK-47",       type: "Assault Rifle" },
  { weaponId: "black-market-ak-m",               weaponName: "Black Market AK-M",               baseModel: "AK-47",       type: "Assault Rifle" },
  { weaponId: "black-market-ak-m-replica",        weaponName: "Black Market AK-M Replica",        baseModel: "AK-47",       type: "Assault Rifle" },
  { weaponId: "aug-a3-cqc",                       weaponName: "AUG A3-CQC",                       baseModel: "AUG",         type: "Assault Rifle" },
  { weaponId: "carbine-7",                        weaponName: "Carbine 7",                        baseModel: "Carbine 7",   type: "Assault Rifle" },
  { weaponId: "f2000",                            weaponName: "F2000",                            baseModel: "F2000",       type: "Assault Rifle" },
  { weaponId: "f2000-replica",                    weaponName: "F2000 Replica",                    baseModel: "F2000",       type: "Assault Rifle" },
  { weaponId: "fal",                              weaponName: "FAL",                              baseModel: "FAL",         type: "Assault Rifle" },
  { weaponId: "fal-sa-58",                        weaponName: "FAL SA-58",                        baseModel: "FAL",         type: "Assault Rifle" },
  { weaponId: "fal-sa-58-para",                   weaponName: "FAL SA-58 Para",                   baseModel: "FAL",         type: "Assault Rifle" },
  { weaponId: "fal-sa-58-para-replica",           weaponName: "FAL SA-58 Para Replica",           baseModel: "FAL",         type: "Assault Rifle" },
  { weaponId: "famas-2010",                       weaponName: "FAMAS 2010",                       baseModel: "FAMAS",       type: "Assault Rifle" },
  { weaponId: "famas-2010-replica",               weaponName: "FAMAS 2010 Replica",               baseModel: "FAMAS",       type: "Assault Rifle" },
  { weaponId: "military-g36",                     weaponName: "Military G36",                     baseModel: "G36",         type: "Assault Rifle" },
  { weaponId: "g36-c",                            weaponName: "G36 C",                            baseModel: "G36",         type: "Assault Rifle" },
  { weaponId: "g36-enhanced",                     weaponName: "G36 Enhanced",                     baseModel: "G36",         type: "Assault Rifle" },
  { weaponId: "g36-enhanced-replica",             weaponName: "G36 Enhanced Replica",             baseModel: "G36",         type: "Assault Rifle" },
  { weaponId: "honey-badger",                     weaponName: "Honey Badger",                     baseModel: "Honey Badger",type: "Assault Rifle" },
  { weaponId: "police-m4",                        weaponName: "Police M4",                        baseModel: "M4",          type: "Assault Rifle" },
  { weaponId: "police-m4-replica",                weaponName: "Police M4 Replica",                baseModel: "M4",          type: "Assault Rifle" },
  { weaponId: "mk16",                             weaponName: "Mk16",                             baseModel: "MK16",        type: "Assault Rifle" },
  { weaponId: "socom-mk16",                       weaponName: "SOCOM Mk16",                       baseModel: "MK16",        type: "Assault Rifle" },
  { weaponId: "tactical-mk-16",                   weaponName: "Tactical Mk 16",                   baseModel: "MK16",        type: "Assault Rifle" },
  { weaponId: "tactical-mk-16-replica",           weaponName: "Tactical Mk 16 Replica",           baseModel: "MK16",        type: "Assault Rifle" },
  { weaponId: "military-p416",                    weaponName: "Military P416",                    baseModel: "P416",        type: "Assault Rifle" },
  { weaponId: "custom-p416-g3",                   weaponName: "Custom P416 G3",                   baseModel: "P416",        type: "Assault Rifle" },
  { weaponId: "pdr",                              weaponName: "PDR",                              baseModel: "PDR",         type: "Assault Rifle" },
  { weaponId: "sig-sauer-556",                    weaponName: "Sig Sauer 556",                    baseModel: "SIG 556",     type: "Assault Rifle" },
  { weaponId: "tkb-408",                          weaponName: "TKB-408",                          baseModel: "TKB-408",     type: "Assault Rifle" },
  { weaponId: "ctar-21",                          weaponName: "CTAR-21",                          baseModel: "CTAR-21",     type: "Assault Rifle" },

  // ── Light Machine Guns ────────────────────────────────────────────────────
  { weaponId: "stoner-lamg",                      weaponName: "Stoner LAMG",                      baseModel: "KAC Stoner",  type: "Light Machine Gun" },
  { weaponId: "military-l86-lsw",                 weaponName: "Military L86 LSW",                 baseModel: "L86",         type: "Light Machine Gun" },
  { weaponId: "custom-l86-a2",                    weaponName: "Custom L86 A2",                    baseModel: "L86",         type: "Light Machine Gun" },
  { weaponId: "custom-l86-a2-replica",            weaponName: "Custom L86 A2 Replica",            baseModel: "L86",         type: "Light Machine Gun" },
  { weaponId: "hk-gr9",                           weaponName: "HK GR9",                           baseModel: "HK GR9",      type: "Light Machine Gun" },
  { weaponId: "m249-b",                           weaponName: "M249 B",                           baseModel: "M249",        type: "Light Machine Gun" },
  { weaponId: "tactical-m249-para",               weaponName: "Tactical M249 Para",               baseModel: "M249",        type: "Light Machine Gun" },
  { weaponId: "military-mk46",                    weaponName: "Military MK46",                    baseModel: "M249",        type: "Light Machine Gun" },
  { weaponId: "military-mk46-replica",            weaponName: "Military MK46 Replica",            baseModel: "M249",        type: "Light Machine Gun" },
  { weaponId: "classic-m60",                      weaponName: "Classic M60",                      baseModel: "M60",         type: "Light Machine Gun" },
  { weaponId: "military-m60-e4",                  weaponName: "Military M60 E4",                  baseModel: "M60",         type: "Light Machine Gun" },
  { weaponId: "black-market-m60-e6",              weaponName: "Black Market M60 E6",              baseModel: "M60",         type: "Light Machine Gun" },
  { weaponId: "classic-m60-replica",              weaponName: "Classic M60 Replica",              baseModel: "M60",         type: "Light Machine Gun" },
  { weaponId: "black-market-m60-e6-replica",      weaponName: "Black Market M60 E6 Replica",      baseModel: "M60",         type: "Light Machine Gun" },
  { weaponId: "mg5",                              weaponName: "MG5",                              baseModel: "MG5",         type: "Light Machine Gun" },
  { weaponId: "infantry-mg5",                     weaponName: "Infantry MG5",                     baseModel: "MG5",         type: "Light Machine Gun" },
  { weaponId: "infantry-mg5-replica",             weaponName: "Infantry MG5 Replica",             baseModel: "MG5",         type: "Light Machine Gun" },
  { weaponId: "iwi-negev",                        weaponName: "IWI NEGEV",                        baseModel: "NEGEV",       type: "Light Machine Gun" },
  { weaponId: "classic-rpk-74",                   weaponName: "Classic RPK-74",                   baseModel: "RPK",         type: "Light Machine Gun" },
  { weaponId: "military-rpk-74",                  weaponName: "Military RPK-74",                  baseModel: "RPK",         type: "Light Machine Gun" },
  { weaponId: "black-market-rpk-74",              weaponName: "Black Market RPK-74",              baseModel: "RPK",         type: "Light Machine Gun" },
  { weaponId: "black-market-rpk-74-replica",      weaponName: "Black Market RPK-74 Replica",      baseModel: "RPK",         type: "Light Machine Gun" },

  // ── Submachine Guns ───────────────────────────────────────────────────────
  { weaponId: "converted-smg-9-a2",              weaponName: "Converted SMG-9 A2",              baseModel: "SMG-9",       type: "Submachine Gun" },
  { weaponId: "converted-smg-9",                  weaponName: "Converted SMG-9",                  baseModel: "SMG-9",       type: "Submachine Gun" },
  { weaponId: "converted-smg-9-replica",          weaponName: "Converted SMG-9 Replica",          baseModel: "SMG-9",       type: "Submachine Gun" },
  { weaponId: "mp5-st",                           weaponName: "MP5 ST",                           baseModel: "MP5",         type: "Submachine Gun" },
  { weaponId: "mp5-st-replica",                   weaponName: "MP5 ST Replica",                   baseModel: "MP5",         type: "Submachine Gun" },
  { weaponId: "mp5a2",                            weaponName: "MP5A2",                            baseModel: "MP5",         type: "Submachine Gun" },
  { weaponId: "mp5-n",                            weaponName: "MP5-N",                            baseModel: "MP5",         type: "Submachine Gun" },
  { weaponId: "cmmg-banshee",                     weaponName: "CMMG Banshee",                     baseModel: "CMMG",        type: "Submachine Gun" },
  { weaponId: "pp-19",                            weaponName: "PP-19",                            baseModel: "PP-19",       type: "Submachine Gun" },
  { weaponId: "enhanced-pp-19",                   weaponName: "Enhanced PP-19",                   baseModel: "PP-19",       type: "Submachine Gun" },
  { weaponId: "aug-a3-para-xs",                   weaponName: "AUG A3 Para XS",                   baseModel: "AUG",         type: "Submachine Gun" },
  { weaponId: "enhanced-aug-a3p",                 weaponName: "Enhanced AUG A3P",                 baseModel: "AUG",         type: "Submachine Gun" },
  { weaponId: "tactical-aug-a3p",                 weaponName: "Tactical AUG A3P",                 baseModel: "AUG",         type: "Submachine Gun" },
  { weaponId: "tactical-aug-a3p-replica",         weaponName: "Tactical AUG A3P Replica",         baseModel: "AUG",         type: "Submachine Gun" },
  { weaponId: "vector-sbr-45-acp",               weaponName: "Vector SBR .45 ACP",               baseModel: "Vector",      type: "Submachine Gun" },
  { weaponId: "vector-sbr-45-acp-replica",        weaponName: "Vector SBR .45 ACP Replica",       baseModel: "Vector",      type: "Submachine Gun" },
  { weaponId: "vector-sbr-9mm",                   weaponName: "Vector SBR 9mm",                   baseModel: "Vector",      type: "Submachine Gun" },
  { weaponId: "tactical-vector-sbr-9mm",          weaponName: "Tactical Vector SBR 9mm",          baseModel: "Vector",      type: "Submachine Gun" },
  { weaponId: "mp7",                              weaponName: "MP7",                              baseModel: "MP7",         type: "Submachine Gun" },
  { weaponId: "police-t821",                      weaponName: "Police T821",                      baseModel: "T821",        type: "Submachine Gun" },
  { weaponId: "black-market-t821",                weaponName: "Black Market T821",                baseModel: "T821",        type: "Submachine Gun" },
  { weaponId: "black-market-t821-replica",        weaponName: "Black Market T821 Replica",        baseModel: "T821",        type: "Submachine Gun" },
  { weaponId: "police-ump-45",                    weaponName: "Police UMP-45",                    baseModel: "UMP-45",      type: "Submachine Gun" },
  { weaponId: "tactical-ump-45",                  weaponName: "Tactical UMP-45",                  baseModel: "UMP-45",      type: "Submachine Gun" },
  { weaponId: "tactical-ump-45-replica",          weaponName: "Tactical UMP-45 Replica",          baseModel: "UMP-45",      type: "Submachine Gun" },
  { weaponId: "m1928",                            weaponName: "M1928",                            baseModel: "Thompson",    type: "Submachine Gun" },
  { weaponId: "tommy-gun",                        weaponName: "Tommy Gun",                        baseModel: "Thompson",    type: "Submachine Gun" },
  { weaponId: "p90",                              weaponName: "P90",                              baseModel: "P90",         type: "Submachine Gun" },
  { weaponId: "p90-replica",                      weaponName: "P90 Replica",                      baseModel: "P90",         type: "Submachine Gun" },
  { weaponId: "mpx",                              weaponName: "MPX",                              baseModel: "MPX",         type: "Submachine Gun" },

  // ── Shotguns ──────────────────────────────────────────────────────────────
  { weaponId: "acs-12",                           weaponName: "ACS-12",                           baseModel: "AA12",        type: "Shotgun" },
  { weaponId: "double-barrel-shotgun",            weaponName: "Double Barrel Shotgun",            baseModel: "Double Barrel",type: "Shotgun" },
  { weaponId: "double-barrel-shotgun-replica",    weaponName: "Double Barrel Shotgun Replica",    baseModel: "Double Barrel",type: "Shotgun" },
  { weaponId: "sawed-off-double-barrel",          weaponName: "Sawed-Off Double Barrel",          baseModel: "Sawed-Off",   type: "Shotgun" },
  { weaponId: "ksg-shotgun",                      weaponName: "KSG Shotgun",                      baseModel: "KSG",         type: "Shotgun" },
  { weaponId: "custom-m870-mcs",                  weaponName: "Custom M870 MCS",                  baseModel: "M870",        type: "Shotgun" },
  { weaponId: "custom-m870-mcs-replica",          weaponName: "Custom M870 MCS Replica",          baseModel: "M870",        type: "Shotgun" },
  { weaponId: "m870-express",                     weaponName: "M870 Express",                     baseModel: "M870",        type: "Shotgun" },
  { weaponId: "m870-express-replica",             weaponName: "M870 Express Replica",             baseModel: "M870",        type: "Shotgun" },
  { weaponId: "military-m870",                    weaponName: "Military M870",                    baseModel: "M870",        type: "Shotgun" },
  { weaponId: "black-market-sasg-12-s",           weaponName: "Black Market SASG-12 S",           baseModel: "SASG-12",     type: "Shotgun" },
  { weaponId: "black-market-sasg-12-s-replica",   weaponName: "Black Market SASG-12 S Replica",   baseModel: "SASG-12",     type: "Shotgun" },
  { weaponId: "sasg-12",                          weaponName: "SASG-12",                          baseModel: "SASG-12",     type: "Shotgun" },
  { weaponId: "tactical-sasg-12-k",               weaponName: "Tactical SASG-12 K",               baseModel: "SASG-12",     type: "Shotgun" },
  { weaponId: "spas-12",                          weaponName: "SPAS-12",                          baseModel: "SPAS-12",     type: "Shotgun" },
  { weaponId: "spas-12-replica",                  weaponName: "SPAS-12 Replica",                  baseModel: "SPAS-12",     type: "Shotgun" },
  { weaponId: "marine-super-90",                  weaponName: "Marine Super 90",                  baseModel: "Super 90",    type: "Shotgun" },
  { weaponId: "super-90",                         weaponName: "Super 90",                         baseModel: "Super 90",    type: "Shotgun" },
  { weaponId: "super-90-replica",                 weaponName: "Super 90 Replica",                 baseModel: "Super 90",    type: "Shotgun" },
  { weaponId: "tactical-super-90-sbs",            weaponName: "Tactical Super 90 SBS",            baseModel: "Super 90",    type: "Shotgun" },
  { weaponId: "tactical-super-90-sbs-replica",    weaponName: "Tactical Super 90 SBS Replica",    baseModel: "Super 90",    type: "Shotgun" },
  { weaponId: "six12",                            weaponName: "Six12",                            baseModel: "Six12",       type: "Shotgun" },

  // ── Rifles ────────────────────────────────────────────────────────────────
  { weaponId: "acr-ss",                           weaponName: "ACR SS",                           baseModel: "ACR",         type: "Rifle" },
  { weaponId: "uic15-mod2",                       weaponName: "UIC15 MOD2",                       baseModel: "AR15",        type: "Rifle" },
  { weaponId: "m16a2",                            weaponName: "M16A2",                            baseModel: "M16",         type: "Rifle" },
  { weaponId: "m16a2-replica",                    weaponName: "M16A2 Replica",                    baseModel: "M16",         type: "Rifle" },
  { weaponId: "classic-m1a",                      weaponName: "Classic M1A",                      baseModel: "M1A",         type: "Rifle" },
  { weaponId: "socom-m1a",                        weaponName: "Socom M1A",                        baseModel: "M1A",         type: "Rifle" },
  { weaponId: "m1a-cqb",                          weaponName: "M1A CQB",                          baseModel: "M1A",         type: "Rifle" },
  { weaponId: "m1a-cqb-replica",                  weaponName: "M1A CQB Replica",                  baseModel: "M1A",         type: "Rifle" },
  { weaponId: "lightweight-m4",                   weaponName: "Lightweight M4",                   baseModel: "M4",          type: "Rifle" },
  { weaponId: "lvoa-c",                           weaponName: "LVOA-C",                           baseModel: "M4",          type: "Rifle" },
  { weaponId: "lvoa-c-replica",                   weaponName: "LVOA-C Replica",                   baseModel: "M4",          type: "Rifle" },
  { weaponId: "urban-mdr",                        weaponName: "Urban MDR",                        baseModel: "MDR",         type: "Rifle" },
  { weaponId: "urban-mdr-replica",                weaponName: "Urban MDR Replica",                baseModel: "MDR",         type: "Rifle" },
  { weaponId: "military-mk17",                    weaponName: "Military MK17",                    baseModel: "Scar",        type: "Rifle" },
  { weaponId: "police-mk17",                      weaponName: "Police MK17",                      baseModel: "Scar",        type: "Rifle" },
  { weaponId: "police-mk17-replica",              weaponName: "Police MK17 Replica",              baseModel: "Scar",        type: "Rifle" },
  { weaponId: "sig-716",                          weaponName: "SIG 716",                          baseModel: "SIG",         type: "Rifle" },
  { weaponId: "sig-716-replica",                  weaponName: "SIG 716 Replica",                  baseModel: "SIG",         type: "Rifle" },
  { weaponId: "sig-716-cqb",                      weaponName: "SIG 716 CQB",                      baseModel: "SIG",         type: "Rifle" },
  { weaponId: "usc-45-acp",                       weaponName: "USC .45 ACP",                      baseModel: "UMP",         type: "Rifle" },
  { weaponId: "usc-45-acp-replica",               weaponName: "USC .45 ACP Replica",              baseModel: "UMP",         type: "Rifle" },
  { weaponId: "resolute-mk47",                    weaponName: "Resolute Mk47",                    baseModel: "MK47",        type: "Rifle" },
  { weaponId: "1886",                             weaponName: "1886",                             baseModel: "1886",        type: "Rifle" },

  // ── Marksman Rifles ───────────────────────────────────────────────────────
  { weaponId: "socom-mk20-ssr",                   weaponName: "SOCOM Mk20 SSR",                   baseModel: "MK20 SSR",    type: "Marksman Rifle" },
  { weaponId: "socom-mk20-ssr-replica",           weaponName: "SOCOM MK20 SSR Replica",           baseModel: "MK20 SSR",    type: "Marksman Rifle" },
  { weaponId: "g28",                              weaponName: "G28",                              baseModel: "G28",         type: "Marksman Rifle" },
  { weaponId: "m700-carbon",                      weaponName: "M700 Carbon",                      baseModel: "M700",        type: "Marksman Rifle" },
  { weaponId: "m700-carbon-replica",              weaponName: "M700 Carbon Replica",              baseModel: "M700",        type: "Marksman Rifle" },
  { weaponId: "m700-tactical",                    weaponName: "M700 Tactical",                    baseModel: "M700",        type: "Marksman Rifle" },
  { weaponId: "model-700",                        weaponName: "Model 700",                        baseModel: "M700",        type: "Marksman Rifle" },
  { weaponId: "model-700-replica",                weaponName: "Model 700 Replica",                baseModel: "M700",        type: "Marksman Rifle" },
  { weaponId: "paratrooper-svd",                  weaponName: "Paratrooper SVD",                  baseModel: "SVD",         type: "Marksman Rifle" },
  { weaponId: "surplus-svd",                      weaponName: "Surplus SVD",                      baseModel: "SVD",         type: "Marksman Rifle" },
  { weaponId: "covert-srs",                       weaponName: "Covert SRS",                       baseModel: "SRS",         type: "Marksman Rifle" },
  { weaponId: "srs-a1",                           weaponName: "SRS A1",                           baseModel: "SRS",         type: "Marksman Rifle" },
  { weaponId: "srs-a1-replica",                   weaponName: "SRS A1 Replica",                   baseModel: "SRS",         type: "Marksman Rifle" },
  { weaponId: "classic-m44-carbine",              weaponName: "Classic M44 Carbine",              baseModel: "M44",         type: "Marksman Rifle" },
  { weaponId: "classic-m44-carbine-replica",      weaponName: "Classic M44 Carbine Replica",      baseModel: "M44",         type: "Marksman Rifle" },
  { weaponId: "hunting-m44",                      weaponName: "Hunting M44",                      baseModel: "M44",         type: "Marksman Rifle" },
  { weaponId: "custom-m44",                       weaponName: "Custom M44",                       baseModel: "M44",         type: "Marksman Rifle" },
  { weaponId: "custom-m44-replica",               weaponName: "Custom M44 Replica",               baseModel: "M44",         type: "Marksman Rifle" },
  { weaponId: "sr-1",                             weaponName: "SR-1",                             baseModel: "DSR-1",       type: "Marksman Rifle" },
  { weaponId: "sr-1-replica",                     weaponName: "SR-1 Replica",                     baseModel: "DSR-1",       type: "Marksman Rifle" },
  { weaponId: "tactical-308",                     weaponName: "Tactical .308",                    baseModel: "Tactical .308",type: "Marksman Rifle" },

  // ── Pistols ───────────────────────────────────────────────────────────────
  { weaponId: "93r",                              weaponName: "93R",                              baseModel: "93R",         type: "Pistol" },
  { weaponId: "d50",                              weaponName: "D50",                              baseModel: "Desert Eagle",type: "Pistol" },
  { weaponId: "m1911",                            weaponName: "M1911",                            baseModel: "M1911",       type: "Pistol" },
  { weaponId: "m45a1",                            weaponName: "M45A1",                            baseModel: "M1911",       type: "Pistol" },
  { weaponId: "tactical-m1911",                   weaponName: "Tactical M1911",                   baseModel: "M1911",       type: "Pistol" },
  { weaponId: "tactical-m1911-replica",           weaponName: "Tactical M1911 Replica",           baseModel: "M1911",       type: "Pistol" },
  { weaponId: "military-m9",                      weaponName: "Military M9",                      baseModel: "M9",          type: "Pistol" },
  { weaponId: "military-m9-replica",              weaponName: "Military M9 Replica",              baseModel: "M9",          type: "Pistol" },
  { weaponId: "officers-m9-a1",                   weaponName: "Officer's M9 A1",                  baseModel: "M9",          type: "Pistol" },
  { weaponId: "custom-pf45",                      weaponName: "Custom PF45",                      baseModel: "PF45",        type: "Pistol" },
  { weaponId: "first-wave-pf45",                  weaponName: "First Wave PF45",                  baseModel: "PF45",        type: "Pistol" },
  { weaponId: "px4-storm-type-f",                 weaponName: "Px4 Storm Type F",                 baseModel: "Px4",         type: "Pistol" },
  { weaponId: "px4-storm-type-t",                 weaponName: "Px4 Storm Type T",                 baseModel: "Px4",         type: "Pistol" },
  { weaponId: "px4-storm-type-t-replica",         weaponName: "Px4 Storm Type T Replica",         baseModel: "Px4",         type: "Pistol" },
  { weaponId: "diceros",                          weaponName: "Diceros",                          baseModel: "Rhino",       type: "Pistol" },
  { weaponId: "diceros-replica",                  weaponName: "Diceros Replica",                  baseModel: "Rhino",       type: "Pistol" },
  { weaponId: "snubnosed-diceros",                weaponName: "Snubnosed Diceros",                baseModel: "Rhino",       type: "Pistol" },
  { weaponId: "586-magnum",                       weaponName: "586 Magnum",                       baseModel: "Magnum",      type: "Pistol" },
  { weaponId: "police-686-magnum",                weaponName: "Police 686 Magnum",                baseModel: "Magnum",      type: "Pistol" },
  { weaponId: "police-686-magnum-replica",        weaponName: "Police 686 Magnum Replica",        baseModel: "Magnum",      type: "Pistol" },
  { weaponId: "x-45",                             weaponName: "X-45",                             baseModel: "X-45",        type: "Pistol" },
  { weaponId: "x-45-tactical",                    weaponName: "X-45 Tactical",                    baseModel: "X-45",        type: "Pistol" },
  { weaponId: "x-45-tactical-replica",            weaponName: "X-45 Tactical Replica",            baseModel: "X-45",        type: "Pistol" },
  { weaponId: "kard-45",                          weaponName: "Kard-45",                          baseModel: "Kriss Kard",  type: "Pistol" },

];

export const HIGH_END_WEAPON_MAP = new Map(
  HIGH_END_WEAPONS.map(w => [w.weaponId, w])
);

export const HIGH_END_WEAPON_NAMES = HIGH_END_WEAPONS.map(w => w.weaponName);
