import type { Rarity, GearSlot } from "./types";
import type { AttrGroup } from "./attributeData";

// ─────────────────────────────────────────────────────────────────────────────
// Slot type primitives
// ─────────────────────────────────────────────────────────────────────────────

/** A core attribute slot on a gear piece */
export type CoreSlot =
  | { type: "any-standard" }
  | { type: "fixed"; name: string };

/** A minor attribute slot on a gear piece */
export type MinorSlot =
  | { type: "fixed"; name: string; value: string }
  | { type: "any-basic" }
  | { type: "any-basic-restricted"; exclude: string[] }
  | { type: "any-basic-group"; group: AttrGroup };

/**
 * A talent slot — only chest and backpack pieces have one.
 * Named items carry a fixed perfect talent; high-end pieces roll any basic talent;
 * exotic pieces carry an exclusive exotic talent. A small number of named pieces
 * allow any basic talent.
 */
export type TalentSlot =
  | { type: "fixed"; talentId: string }
  | { type: "any-basic" };

// ─────────────────────────────────────────────────────────────────────────────
// Named / Exotic / High-End gear item
// ─────────────────────────────────────────────────────────────────────────────

export interface NamedGearItem {
  gearId:         string;         // kebab-case unique ID
  gearName:       string;
  slot:           GearSlot;
  brand:          string;         // matches BrandDef.name or GearSetDef.name
  rarity:         Rarity;
  /** Fixed perk description present on named and exotic items */
  namedPerkDesc?: string;
  /** Talent slot — chest and backpack pieces only */
  talent?:        TalentSlot;
  /** 1–3 core attribute slots (Ninjabike Messenger Backpack has all 3 simultaneously) */
  cores:          CoreSlot[];
  /** 0–3 minor attribute slots */
  minors:         MinorSlot[];
  /** Number of gear mod slots (0–2); only mask, backpack, and chest can have mod slots */
  modSlots:       number;
  source:         string;
  flavorText?:    string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Data
// ─────────────────────────────────────────────────────────────────────────────

export const NAMED_GEAR: NamedGearItem[] = [

  // ── Masks ──────────────────────────────────────────────────────────────────

  {
    gearId: "punch-drunk",
    gearName: "Punch Drunk",
    slot: "mask",
    brand: "Douglas & Harding",
    rarity: "Named",
    namedPerkDesc: "Extra Headshot Damage",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Headshot Damage", value: "20%" },
      { type: "any-basic-restricted", exclude: ["Headshot Damage"] },
    ],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"If the first shot doesn't drop 'em, the second one will. Or the third, third's usually good.\"",
  },
  {
    gearId: "nightwatcher",
    gearName: "Nightwatcher",
    slot: "mask",
    brand: "Gila Guard",
    rarity: "Named",
    namedPerkDesc: "Scanner Pulse Haste",
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Scanner Pulse Haste", value: "100%" },
      { type: "any-basic" },
    ],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Through glass and steel; looking at you; a view so cruel.\"",
  },
  {
    gearId: "chill-out",
    gearName: "Chill Out",
    slot: "mask",
    brand: "Gila Guard",
    rarity: "Named",
    namedPerkDesc: "Has 2 Mod Slots and only 1 Minor Stat",
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }],
    modSlots: 2,
    source: "Special Event Hoarder",
    flavorText: "\"Revenge is a dish best served cold.\" - Someone who remembers you",
  },
  {
    gearId: "visionario",
    gearName: "Visionario",
    slot: "mask",
    brand: "Legatus S.p.A.",
    rarity: "Named",
    namedPerkDesc: "Extra optimal range",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Optimal Range", value: "50%" },
      { type: "any-basic" },
    ],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"So far be distant; and good night, sweet friend\" - A Midsummer Night's Dream",
  },
  {
    gearId: "the-hollow-man",
    gearName: "The Hollow Man",
    slot: "mask",
    brand: "Yaahl Gear",
    rarity: "Named",
    namedPerkDesc: "Damage to Health",
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Damage to Health", value: "14%" },
      { type: "any-basic" },
    ],
    modSlots: 1,
    source: "DZ",
    flavorText: "\"No whimper. No bang. Just silence. The end of all things.\"",
  },

  // ── Exotic Masks ───────────────────────────────────────────────────────────

  {
    gearId: "vile",
    gearName: "Vile",
    slot: "mask",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Status effects also apply a damage over time debuff for 10s. Total Damage dealt is equal to 50% of your concussion grenade damage and increased by your status effect attributes.",
    talent:   { type: "fixed", talentId: "toxic-delivery" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Status Effects",      value: "5% – 10%" },
      { type: "fixed", name: "Hazard Protection",   value: "5% – 10%" },
    ],
    modSlots: 1,
    source: "Season 3 Track / Target Loot / Exotic Caches",
    flavorText: "\"You cling to life like a rebellious teen resisting curfew. But death is patient... and so am I.\" - Dr Vilts, BTSU Physician",
  },
  {
    gearId: "catharsis",
    gearName: "Catharsis",
    slot: "mask",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Taking damage builds stacks to a cap of 30. Each stack grants 1.5% Weapon Damage. Total Damage at max stacks triggers a purge, removing all stacks and Status Effects and then dropping a healing cloud which restores 5% of Max Armor for 10s to all allies in the cloud.",
    talent:   { type: "fixed", talentId: "vicious-cycle" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Incoming Repairs",    value: "7.8% – 20%" },
      { type: "fixed", name: "Armor Regeneration",  value: "1689 – 4925" },
    ],
    modSlots: 1,
    source: "Season 9 Track (TU15) / Target Loot / Exotic Caches",
    flavorText: "\"The establishment does everything in its power to ensure that revolutionary rage is redirected into empty outlets which provide pressure releases for desires that could become dangerous if allowed to progress\" - George L. Jackson",
  },
  {
    gearId: "coyotes-mask",
    gearName: "Coyote's Mask",
    slot: "mask",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "You and all allies gain a bonus based on the distance of the last enemy you hit. 0-15m: +25% critical hit damage. 15-25m: +10% critical hit chance and +10% critical hit damage. 25m+: +25% critical hit Chance.",
    talent:   { type: "fixed", talentId: "pack-instincts" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%" },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%" },
    ],
    modSlots: 1,
    source: "Season 1 Track / Coyote at Jefferson Trade Centre / Target Loot / Exotic Caches",
    flavorText: "\"Lived through this bullet. I'll live through yours.\" - Coyote",
  },
  {
    gearId: "catalyst",
    gearName: "Catalyst",
    slot: "mask",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Catalysis: Dealing and receiving status effects builds stacks to a maximum of 12. Each stack grants +2% Weapon Damage and +2% Status Effects. Each enemy within 25m affected by a status effect grants +1 stack/sec; being affected yourself grants +2 stacks/sec. Stacks decay at 1/sec after 5s if no enemies are in radius or you are affected by status effects. | Reactant: At max stacks, killing a status-affected enemy grants for 5s: +25% bonus armor, +20% reload speed. | Stabilizer: While burning, you can maintain ADS without disruption.",
    talent:   { type: "fixed", talentId: "chemical-agent" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Hazard Protection", value: "5% – 10%" },
      { type: "fixed", name: "Status Effects",    value: "5% – 10%" },
    ],
    modSlots: 1,
    source: "LM-21 \"Marauder\" Army Terminal / Brooklyn Open World Named Bosses",
    flavorText: "\"We're still being tested. The only constant variable is fire\"",
  },
  {
    gearId: "tinkerer",
    gearName: "Tinkerer",
    slot: "mask",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "If your Primary and Secondary weapon are not Exotic or Named and of the same type, the Secondary Weapon's talent will also be applied to the Primary Weapon. Doesn't apply to talents that include Weapon Swapping.",
    talent:   { type: "fixed", talentId: "abridged" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%" },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%" },
    ],
    modSlots: 1,
    source: "Y7S1 Climax Mission (Master guaranteed / any difficulty drop)",
    flavorText: "\"Why not both.\"",
  },

  // ── Backpacks ──────────────────────────────────────────────────────────────

  {
    gearId: "liquid-engineer",
    gearName: "Liquid Engineer",
    slot: "backpack",
    brand: "Belstone Armory",
    rarity: "Named",
    namedPerkDesc: "Killing an enemy adds and refreshes a stack of +12% bonus armor for 10s. Max stack is 10.",
    talent:   { type: "fixed", talentId: "perfect-bloodsucker" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "DZ",
    flavorText: "\"Is that oil, or blood?\" -BTSU Combat Medic",
  },
  {
    gearId: "hermano",
    gearName: "Hermano",
    slot: "backpack",
    brand: "Brazos de Arcabuz",
    rarity: "Named",
    namedPerkDesc: "You and allies within 15m of your deployed skills gain +30% reload speed and reduces active cooldowns by 0.6 each second.",
    talent:   { type: "fixed", talentId: "perfect-overclock" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
  },
  {
    gearId: "the-courier",
    gearName: "The Courier",
    slot: "backpack",
    brand: "Habsburg Guard",
    rarity: "Named",
    namedPerkDesc: "When you apply a status effect, it is also applied to all enemies within 10m of your target. Cooldown: 10s.",
    talent:   { type: "fixed", talentId: "perfect-creeping-death" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"May this carry your soul to paradise\" -The Priest",
  },
  {
    gearId: "backbone",
    gearName: "Backbone",
    slot: "backpack",
    brand: "Lengmo",
    rarity: "Named",
    namedPerkDesc: "Killing an enemy increases total weapon damage by 7% for 15s. Stacks up to 5. Grenade kills add 2 stacks.",
    talent:   { type: "fixed", talentId: "perfectly-unstoppable-force" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Your first kill is hard. But it gets easier the more you do it.\" - The Strategist",
  },
  {
    gearId: "anarchists-cookbook",
    gearName: "Anarchist's Cookbook",
    slot: "backpack",
    brand: "Golan Gear Ltd",
    rarity: "Named",
    namedPerkDesc: "Applying a status effect increases total weapon damage by 18% for 27s.",
    talent:   { type: "fixed", talentId: "perfectly-wicked" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ / DZ / Warlords Campaign (Vivian Conley story)",
    flavorText: "\"Conley, I think you'll find some great toys in here. Try not to blow everything up while you're looking through it.\" - Aaron Keener",
  },
  {
    gearId: "strategic-alignment",
    gearName: "Strategic Alignment",
    slot: "backpack",
    brand: "China Light Industries Corp.",
    rarity: "Named",
    namedPerkDesc: "Applying a status effect to an enemy increases total skill damage and repair by 20% for 27s.",
    talent:   { type: "fixed", talentId: "perfect-shock-and-awe" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"I know this is going to look like we're destroying everything. Don't worry about it. We don't make mistakes. Just happy accidents.\" - Bob Ross",
  },
  {
    gearId: "lavoisier",
    gearName: "Lavoisier",
    slot: "backpack",
    brand: "Electrique",
    rarity: "Named",
    namedPerkDesc: "Applying Blind, Ensnare, Confuse, or Shock to an enemy grants 50% of your armor as bonus armor to you and all allies within 30 meters of that enemy for 10 seconds.",
    talent:   { type: "fixed", talentId: "perfect-galvanize" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"A piece of perfection, if you understand what you can do with it.\" Anonymous",
  },
  {
    gearId: "matador",
    gearName: "Matador",
    slot: "backpack",
    brand: "Walker, Harris & Co.",
    rarity: "Named",
    namedPerkDesc: "When you are within 10m of an enemy, gain 23% bonus armor for 5s. Stacks up to 3 times. Cooldown: 5s.",
    talent:   { type: "fixed", talentId: "perfect-adrenaline-rush" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }],
    modSlots: 1,
    source: "DZ",
    flavorText: "\"I used to dance with death itself, but grew tired of the performance. I think I prefer having the odds stacked against me instead.\" - The Bull",
  },
  {
    gearId: "the-gift",
    gearName: "The Gift",
    slot: "backpack",
    brand: "Providence Defense",
    rarity: "Named",
    namedPerkDesc: "Increases total weapon damage by 25%. Taking damage disables buff for 3s.",
    talent:   { type: "fixed", talentId: "perfect-vigilance" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }],
    modSlots: 1,
    source: "DZ",
    flavorText: "\"Only after everything has been taken from you, can you learn to give. When the vessel is full, the soul is empty.\" - Unknown",
  },
  {
    gearId: "percussive-maintenance",
    gearName: "Percussive Maintenance",
    slot: "backpack",
    brand: "Alps Summit Armament",
    rarity: "Named",
    namedPerkDesc: "Skill kills increase total skill damage by 25% for 27s.",
    talent:   { type: "fixed", talentId: "perfect-tech-support" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Have you tried turning it off and on again?\" (note: don't turn your devices on and off. Use the Restart function to solve problems instead. They have different functions.)",
  },
  {
    gearId: "vigil",
    gearName: "Vigil",
    slot: "backpack",
    brand: "Legatus S.p.A.",
    rarity: "Named",
    namedPerkDesc: "Amplifies total weapon damage for 10s when swapping between your primary and secondary weapons if they are different. 45% to enemies within 15m for Shotguns and SMGs. 45% to enemies further than 25m for Rifles and MMRs. 20% to enemies between 15-25m for LMGs and ARs. At most once per 5s per weapon type.",
    talent:   { type: "fixed", talentId: "perfect-versatile" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Honor the fallen.\"",
  },
  {
    gearId: "devils-due",
    gearName: "Devil's Due",
    slot: "backpack",
    brand: "Česká Výroba s.r.o.",
    rarity: "Named",
    namedPerkDesc: "When you are below 20% armor, critical hits repair 2.5% of missing armour. On kill, critical hits repair 2.5% of missing armour. Lowest possible repair is 0% armour. Each red core attribute adds 1 second to the time. Maximum is 10 seconds.",
    talent:   { type: "fixed", talentId: "perfect-clutch" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "DZ",
    flavorText: "\"When he comes calling / It's best not be stalling / Or you might find yourself falling / Down, down, down below\" - Inscription inside the pack",
  },
  {
    gearId: "battery-pack",
    gearName: "Battery Pack",
    slot: "backpack",
    brand: "Empress International",
    rarity: "Named",
    namedPerkDesc: "Kills from cover reduce skill cooldowns by 15%.",
    talent:   { type: "fixed", talentId: "perfectly-calculated" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
  },
  {
    gearId: "the-setup",
    gearName: "The Setup",
    slot: "backpack",
    brand: "Uzina Getica",
    rarity: "Named",
    namedPerkDesc: "Enemies you hit with shotguns and marksman rifles amplifies the damage they take by 15% from all sources for 5s.",
    talent:   { type: "fixed", talentId: "perfectly-opportunistic" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
  },
  {
    gearId: "force-multiplier",
    gearName: "Force Multiplier",
    slot: "backpack",
    brand: "Hana-U Corporation",
    rarity: "Named",
    namedPerkDesc: "Enemies that walk within 3 meters of your Hive, Turret, Remote Pulse or Decoy are shocked.",
    talent:   { type: "fixed", talentId: "perfect-combined-arms" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"You've got to think about force multipliers in this line of work. You don't always have backup, so make use of what's available.\" - SHD Training Guide",
  },
  {
    gearId: "proxy",
    gearName: "Proxy",
    slot: "backpack",
    brand: "Palisade Steelworks",
    rarity: "Named",
    namedPerkDesc: "Arm time: 2 seconds. Cooldown per Skill: 8 seconds.",
    talent:   { type: "fixed", talentId: "perfectly-tamper-proof" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Hostile detected. Hostile Eliminated.\" -Alexander Ortiz",
  },
  {
    gearId: "axel",
    gearName: "Axel",
    slot: "backpack",
    brand: "Shiny Monkey Gear",
    rarity: "Named",
    namedPerkDesc: "Using an armor kit grants +1 Skill Tier for 15s. If already at Skill Tier 6, grants Overcharge. Cooldown 10s.",
    talent:   { type: "fixed", talentId: "perfect-energize" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Don't fear your instincts, Society taught you how to fall.\"",
  },
  {
    gearId: "capn",
    gearName: "Cap'n",
    slot: "backpack",
    brand: "Imminence Armaments",
    rarity: "Named",
    namedPerkDesc: "Performing a cover to cover grants 20% of your armor as bonus armor to you and all allies for 10s. This is Tripled if you end within 10m of an enemy. Cooldown: 10s.",
    talent:   { type: "fixed", talentId: "perfect-leadership" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Get behind me.\"",
  },
  {
    gearId: "festive-delivery",
    gearName: "Festive Delivery",
    slot: "backpack",
    brand: "Grupo Sombra S.A.",
    rarity: "Named",
    namedPerkDesc: "Concussion grenades become Festive Grenades. Hitting an enemy with a Festive Grenade will cause explosions to happen around two other enemies within 20m, 10m in PvP. *Dealing 15% damage in PvP.",
    talent:   { type: "fixed", talentId: "fireworks-show" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "Special Event Hoarder",
    flavorText: "\"You get fireworks, and you get fireworks. Everybody gets fireworks!\"",
  },

  // ── Exotic Backpacks ───────────────────────────────────────────────────────

  {
    gearId: "acostas-go-bag",
    gearName: "Acosta's Go-Bag",
    slot: "backpack",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "One in the Hand...: Throwing a grenade refunds it and grants +1 Skill Tier for 15s. Grants Overcharge if already at Skill Tier 6. Cooldown: 60s. | ...Two in the Bag: +1 Armor Kit Capacity, +3 Grenade Capacity, +25% Ammo Capacity, +10% Repair Skills, +10% Status Effects.",
    talent:   { type: "fixed", talentId: "one-in-the-hand" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Skill Damage", value: "1.3% – 10%" },
      { type: "fixed", name: "Skill Haste",  value: "6% – 12%"  },
    ],
    modSlots: 1,
    source: "Faction Lockboxes (3%) / Target Loot / Exotic Caches",
    flavorText: "\"You never know what you're going to need, so it's best to be prepared.\" - Eva Acosta, Urban Spelunker",
  },
  {
    gearId: "birdies-quick-fix-pack",
    gearName: "Birdie's Quick Fix Pack",
    slot: "backpack",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "+80% Revive Speed, -50% Weakened Debuff timer, +45% Hive efficiency. Provides +50% damage resistance to both agents while reviving or being revived, and for 5s after a successful Hive Revive, or 10s after a Manual Revive. Any successful revives provide +1 Skill Tier for 5s. Revives at Skill Tier 6 grant Overcharge for 15s.",
    talent:   { type: "fixed", talentId: "combat-medic" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Skill Haste",    value: "6% – 12%"   },
      { type: "fixed", name: "Repair Skills",  value: "7.8% – 20%" },
    ],
    modSlots: 1,
    source: "Y6S3 Climax Mission (Master guaranteed / any difficulty drop)",
    flavorText: "\"Get up, we're out of body bags.\"",
  },
  {
    gearId: "memento",
    gearName: "Memento",
    slot: "backpack",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Enemies you kill drop a trophy on death. Collecting trophies provides both a short and long term buff, the first of which scales with the number of core attributes equipped and lasts 10s. Red Core: -5% Weapon Damage. Blue Core: -10% Bonus Armor. Yellow Core: -5% Skill Efficiency. For every trophy collected gain an additional +1% weapon damage, +1% skill efficiency and +0.1% armor regeneration for 300s. Maximum 30 stacks.",
    talent:   { type: "fixed", talentId: "kill-confirmed" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Armor",      value: "16,594 – 170,000" },
      { type: "fixed", name: "Skill Tier", value: "+1"               },
    ],
    modSlots: 1,
    source: "Season 3 Track / Target Loot / Exotic Caches",
    flavorText: "\"I took from those who watched, hunted, and collected, until only their shadows remained. Now my watch has ended, so yours may begin.\" - Inscription by an unknown author",
  },
  {
    gearId: "ninjabike-messenger-backpack",
    gearName: "NinjaBike Messenger Backpack",
    slot: "backpack",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Slots in with any equipped Gear Set and/or Brand Set item to fulfill a requirement towards unlocking a Gear and/or Brand Sets bonus. Can unlock bonuses from multiple sets simultaneously.",
    talent:   { type: "fixed", talentId: "resourceful" },
    cores:    [
      { type: "fixed", name: "Weapon Damage" },
      { type: "fixed", name: "Armor" },
      { type: "fixed", name: "Skill Tier" },
    ],
    minors:   [],
    modSlots: 1,
    source: "Season 11 Reward Track / Target Loot / Exotic Caches",
    flavorText: "\"From the depths of hell, this has been resurrected as if it cannot die.\" The Priest",
  },

  // ── Chests ─────────────────────────────────────────────────────────────────

  {
    gearId: "henri",
    gearName: "Henri",
    slot: "chest",
    brand: "Electrique",
    rarity: "Named",
    namedPerkDesc: "While you are within 10m of an ally or skill, total weapon damage is increased by 20%.",
    talent:   { type: "fixed", talentId: "perfect-companion" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"We live together, we learn together, we die together. But, first we make each other stronger.\" Anonymous",
  },
  {
    gearId: "hunter-killer",
    gearName: "Hunter-Killer",
    slot: "chest",
    brand: "Golan Gear Ltd",
    rarity: "Named",
    namedPerkDesc: "While you have bonus armour, gain 3 stacks each second up to a max of 10. Each stack increases total weapon damage by 4% to enemies within 10m. All stacks are lost when you have no bonus armour.",
    talent:   { type: "fixed", talentId: "perfect-intimidate" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "Off-White Cache / Cassie Mendoza",
    flavorText: "\"These guys came out of nowhere. Dressed to kill and armed to the teeth. Turns out, we were the ones they were sent to kill.\" - Division Agent",
  },
  {
    gearId: "everyday-carrier",
    gearName: "Everyday Carrier",
    slot: "chest",
    brand: "Belstone Armory",
    rarity: "Named",
    namedPerkDesc: "Using an armor kit has a 75% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 100%. Requires 10 seconds to arm talent.",
    talent:   { type: "fixed", talentId: "perfectly-efficient" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"What's in my everyday carry? As many armour plates as I can fit\" - Agent Sanders",
  },
  {
    gearId: "chainkiller",
    gearName: "Chainkiller",
    slot: "chest",
    brand: "Walker, Harris & Co.",
    rarity: "Named",
    namedPerkDesc: "After killing an enemy with a headshot, your next weapon hit within 30s deals 150% of that killing blow's damage in addition to it. Damage is capped to 800% of your weapon damage. This is raised to 1250% if your headshot damage is greater than 150%.",
    talent:   { type: "fixed", talentId: "perfect-headhunter" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Ninety-nine bottles of beer on the wall, ninety-nine bottles of beer. Shoot one down, watch it explode, ninety-eight bottles of beer on the wall...\" - Bored True Sons Marksman",
  },
  {
    gearId: "pointman",
    gearName: "Pointman",
    slot: "chest",
    brand: "Gila Guard",
    rarity: "Named",
    namedPerkDesc: "Deploying a shield makes it invulnerable for 5s and grants 50% of your armor as bonus armor to all other allies for 20s. Cooldown: 25s.",
    talent:   { type: "fixed", talentId: "perfect-vanguard" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ / Warlords Campaign (James Dragov story)",
    flavorText: "\"Knuckles, Ron, you're with me. Duchess, you're on point. Here, take this. Maybe it'll save yer ass.\" - James Dragov",
  },
  {
    gearId: "vedmedytsya-vest",
    gearName: "Vedmedytsya Vest",
    slot: "chest",
    brand: "Petrov Defense Group",
    rarity: "Named",
    namedPerkDesc: "While in cover weapon handling is increased by +50%.",
    talent:   { type: "fixed", talentId: "perfect-braced" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "Crafted",
    flavorText: "Brace yourself. Stand firm against the tide of history.",
  },
  {
    gearId: "the-sacrifice",
    gearName: "The Sacrifice",
    slot: "chest",
    brand: "Providence Defense",
    rarity: "Named",
    namedPerkDesc: "All damage you deal is amplified by 30%. All damage you take is amplified by 60%.",
    talent:   { type: "fixed", talentId: "perfect-glass-cannon" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Only after everything has been given, can you expect to receive. When the vessel is empty, the soul is complete.\"",
  },
  {
    gearId: "zero-fs",
    gearName: "Zero F's",
    slot: "chest",
    brand: "Badger Tuff",
    rarity: "Named",
    namedPerkDesc: "When your armor is depleted, repair 100% of your armor. Cooldown: 55s.",
    talent:   { type: "fixed", talentId: "perfect-unbreakable" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Behold! The field in which I grow my fucks. Lay thine eyes upon it and see that it is barren.\"",
  },
  {
    gearId: "ferocious-calm",
    gearName: "Ferocious Calm",
    slot: "chest",
    brand: "Fenris Group AB",
    rarity: "Named",
    namedPerkDesc: "After staying in cover for 8 seconds, increase your and all allies' total weapon and skill damage by 14% as long as you remain in cover, or in a cover to cover move.",
    talent:   { type: "fixed", talentId: "perfect-overwatch" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "DZ",
    flavorText: "\"The invention of the gun required a redefinition of courage from aggressive ferocity to calmness under fire\" - Robert L. O'Connell",
  },
  {
    gearId: "door-kickers-knock",
    gearName: "Door-Kicker's Knock",
    slot: "chest",
    brand: "Grupo Sombra S.A.",
    rarity: "Named",
    namedPerkDesc: "Damaging an enemy with a skill increases total weapon damage by 18% for 20 seconds.",
    talent:   { type: "fixed", talentId: "perfect-spark" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "DZ",
    flavorText: "\"Just drop your seeker and let it go. Don't let the bang trip you up. You've got to prepare for the shock.\" - SHD Training Guide",
  },
  {
    gearId: "caesars-guard",
    gearName: "Caesar's Guard",
    slot: "chest",
    brand: "Empress International",
    rarity: "Named",
    namedPerkDesc: "Skill kills have a 30% chance to reset skill cooldowns.",
    talent:   { type: "fixed", talentId: "perfectly-skilled" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
  },
  {
    gearId: "closer",
    gearName: "Closer",
    slot: "chest",
    brand: "Uzina Getica",
    rarity: "Named",
    namedPerkDesc: "Amplifies total weapon and skill damage by 20% to pulsed enemies.",
    talent:   { type: "fixed", talentId: "perfect-spotter" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
  },
  {
    gearId: "cherished",
    gearName: "Cherished",
    slot: "chest",
    brand: "Habsburg Guard",
    rarity: "Named",
    namedPerkDesc: "Applies blind to enemy hit in the head. Cooldown 20 seconds. Applies bleed to an enemy hit in the chest. Cooldown 20 seconds.",
    talent:   { type: "fixed", talentId: "perfect-trauma" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"My gift to you, to protect your sacred heart.\" The Priest",
  },
  {
    gearId: "carpenter",
    gearName: "Carpenter",
    slot: "chest",
    brand: "Lengmo",
    rarity: "Named",
    namedPerkDesc: "Grenade Radius is increased by 75%. Grenades that kill an enemy are refunded. Grenades can now be \"cooked\" by holding the fire button, making them explode earlier. Gain 15% bonus armor while aiming grenades.",
    talent:   { type: "fixed", talentId: "perfectly-mad-bomber" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"The things I break stay broken.\" - The Strategist",
  },
  {
    gearId: "bober",
    gearName: "Bober",
    slot: "chest",
    brand: "Zwiadowka Sp. z o.o.",
    rarity: "Named",
    namedPerkDesc: "If you are below 30% Armor, headshots from cover repair 30% of your armor. Cooldown 2 seconds.",
    talent:   { type: "fixed", talentId: "perfect-entrench" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"No way they can get me in this.\" - Diesel",
  },
  {
    gearId: "pristine-example",
    gearName: "Pristine Example",
    slot: "chest",
    brand: "Airaldi Holdings",
    rarity: "Named",
    namedPerkDesc: "Increases total weapon damage by 6% every second you are aiming while scoped 8x or higher, up to 60%.",
    talent:   { type: "fixed", talentId: "perfect-focus" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"Only the first shot is clean. Everything after that is just messy.\"",
  },
  {
    gearId: "sleight",
    gearName: "Sleight",
    slot: "chest",
    brand: "Urban Lookout",
    rarity: "Named",
    namedPerkDesc: "Grants +40% bonus armor while reloading. Grants 0-30% of your armor as bonus armor to all other allies when they are reloading, based on your Blue core attribute.",
    talent:   { type: "fixed", talentId: "perfect-protected-reload" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"I'm feeling generous.\"",
  },
  {
    gearId: "combustor",
    gearName: "Combustor",
    slot: "chest",
    brand: "Palisade Steelworks",
    rarity: "Named",
    namedPerkDesc: "Whenever you throw a skill, 1.5 seconds after landing, it creates an explosion damaging enemies within 5m. Afterwards explosions will occur every 5s. Damage scales with skill tier dealing 25-100% damage of a concussion grenade. Occurs once per skill. Applies to Remote Pulse, All Turrets, All Hives, Explosive Seeker, Cluster Seeker, Mender Seeker, Decoy, All Traps.",
    talent:   { type: "fixed", talentId: "perfectly-explosive-delivery" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
    flavorText: "\"My operatives would never be left alone in the field\" - Natalya Sokolova",
  },
  {
    gearId: "equalizer",
    gearName: "Equalizer",
    slot: "chest",
    brand: "Unit Alloys",
    rarity: "Named",
    namedPerkDesc: "Critical hits increase total weapon damage by 1% for 10s. Stacks up to 24 times.",
    talent:   { type: "fixed", talentId: "perfect-obliterate" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }],
    modSlots: 1,
    source: "LZ",
  },

  // ── Exotic Chests ──────────────────────────────────────────────────────────

  {
    gearId: "collector",
    gearName: "Collector",
    slot: "chest",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "+3 Grenade Capacity, +50% Grenade Radius, +35% Grenade Damage, +25% Grenade Damage for each extra enemy caught in the blast. Automatically regenerate grenades every 30s if you have less than 2 grenades in your inventory.",
    talent:   { type: "fixed", talentId: "hoarder" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 1,
    source: "Year 5 Season 2 Track / Target Loot / Exotic Caches",
    flavorText: "\"Let's see the Division glue you back together after this.\" - The Strategist",
  },
  {
    gearId: "provocator",
    gearName: "Provocator",
    slot: "chest",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Receive +25% Damage resistance from enemies within 20m.",
    talent:   { type: "fixed", talentId: "challenger" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Armor Regeneration", value: "1689 – 4925" },
      { type: "fixed", name: "Hazard Protection",  value: "5% – 10%"   },
    ],
    modSlots: 1,
    source: "Y6S2 Climax Mission (Master guaranteed / any difficulty drop)",
    flavorText: "\"One does not simply wear red into battle. A red knight is not afraid but ready to provoke.\" - Anonymous",
  },
  {
    gearId: "beacon",
    gearName: "Beacon",
    slot: "chest",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Both you and Allies receive +30% Critical Hit Damage, +15% Skill Efficiency and +2% Armor Regen when an Ally is within 10m of you. Receive +15% Critical Hit Damage, +7.5% Skill Efficiency and +1% Armor Regen when one of your Skills is within 10m of you. Only the highest group of buffs can be active at one time.",
    talent:   { type: "fixed", talentId: "bond" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 1,
    source: "",
    flavorText: "\"With Me.\"",
  },
  {
    gearId: "tardigrade-armor-system",
    gearName: "Tardigrade Armor System",
    slot: "chest",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Whenever you or any ally's armor breaks, they gain 80% of your armor as bonus armor for 10s. Cooldown per ally: 45s. Killing an enemy with your specialization weapon removes this cooldown for all allies.",
    talent:   { type: "fixed", talentId: "ablative-nano-plating" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Armor Regeneration", value: "1689 – 4925" },
      { type: "fixed", name: "Explosive Resistance", value: "1% – 10%"  },
    ],
    modSlots: 1,
    source: "True Sons Bosses / Target Loot / Exotic Caches",
    flavorText: "An evolution of the reactive armour concept, ablative nano-plating was initially designed as a prototype technology for self-repairing heat shields on aircraft repeatedly entering and exiting planetary atmospheres.",
  },
  {
    gearId: "ridgeways-pride",
    gearName: "Ridgeway's Pride",
    slot: "chest",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Shooting enemies within 15m applies bleed to the target. Repair 3-48% of your armor per second for every enemy that is bleeding within 15m. Repair strength per number of bleeding enemies — 1:3% 2:6% 3:12% 4:24% 5:48%.",
    talent:   { type: "fixed", talentId: "bleeding-edge" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 1,
    source: "The Summit (floor blueprints 1-100) / Target Loot / Exotic Caches",
    flavorText: "\"You can tell a lot about a man by the way he bleeds. Me? I bleed for my country, and nothing else.\" - General Antwon Ridgeway",
  },

  // ── Gloves ─────────────────────────────────────────────────────────────────

  {
    gearId: "deathgrips",
    gearName: "Deathgrips",
    slot: "gloves",
    brand: "5.11 Tactical",
    rarity: "Named",
    namedPerkDesc: "Armor on Kill",
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Armor on Kill", value: "10%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "DZ",
    flavorText: "\"Most people are white-knuckling their way through life, stress levels off the charts. Working dead-end jobs paying off their loans, student debts and fucking lattes. That shit will kill you without clarity in your life, and nothing brings clarity like hanging off the side of a mountain.\"",
  },
  {
    gearId: "contractors-gloves",
    gearName: "Contractor's Gloves",
    slot: "gloves",
    brand: "Petrov Defense Group",
    rarity: "Named",
    namedPerkDesc: "Damage to Armor",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Damage to Armor", value: "8%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"Never met a man I couldn't break. Apply enough pressure on a small enough point, and anything cracks.\"",
  },
  {
    gearId: "motherly-love",
    gearName: "Motherly Love",
    slot: "gloves",
    brand: "Alps Summit Armament",
    rarity: "Named",
    namedPerkDesc: "Skill Health",
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Skill Health", value: "25%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "Crafted",
    flavorText: "\"Life is horrible. Once you realise that, it's easier to appreciate the moments that are the exceptions. Makes it all a bit more realistic to endure.\"",
  },
  {
    gearId: "eagles-grasp",
    gearName: "Eagles Grasp",
    slot: "gloves",
    brand: "Zwiadowka Sp. z o.o.",
    rarity: "Named",
    namedPerkDesc: "Weapon Handling",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Weapon Handling", value: "15%" },
      { type: "any-basic-restricted", exclude: ["Weapon Handling"] },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"Just wait until I get my hands on them.\" - Saint",
  },
  {
    gearId: "firm-handshake",
    gearName: "Firm Handshake",
    slot: "gloves",
    brand: "Sokolov Concern",
    rarity: "Named",
    namedPerkDesc: "Extra Status Effects",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Status Effects", value: "16%" },
      { type: "any-basic-restricted", exclude: ["Status Effects"] },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"You can tell a lot about a person from their handshake. It's also a great pathogenic delivery system.\"",
  },

  // ── Exotic Gloves ──────────────────────────────────────────────────────────

  {
    gearId: "bloody-knuckles",
    gearName: "Bloody Knuckles",
    slot: "gloves",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Red. Seeing Red grants +25% weapon damage and +100% melee damage. Seeing Red lasts 20 seconds and starts a 60 second cooldown after completion. While in cooldown, damaging an enemy with a melee attack or hitting an enemy with the effect of a grenade will complete the cooldown instantly. (Note: the 25% 'weapon damage' buff actually gives total weapon damage.)",
    talent:   { type: "fixed", talentId: "over-the-top" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "Season 10 Track (TU16) / Target Loot / Exotic Caches",
    flavorText: "\"A broken watch is still a good memento.\" 13",
  },
  {
    gearId: "btsu-datagloves",
    gearName: "BTSU Datagloves",
    slot: "gloves",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Grants 15% Hive skill haste per skill tier. Detonating a hive refreshes your skill cooldowns and grants overcharge for 15s. If at Skill Tier 6, this effect also applies to all allies. Allies receiving this effect are unable to benefit from it again for 120s.",
    talent:   { type: "fixed", talentId: "transference-overclock" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Skill Haste",    value: "6% – 12%"   },
      { type: "fixed", name: "Repair Skills",  value: "7.8% – 20%" },
    ],
    modSlots: 0,
    source: "Black Tusk Medics / Galveston, Camp White Oak / Target Loot / Exotic Caches",
    flavorText: "\"Pop always told me 'son, you're only as good as the tools you work with.' So I chose to work with the best tools.\" - Galveston",
  },
  {
    gearId: "exodus-gloves",
    gearName: "Exodus Gloves",
    slot: "gloves",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "On Armor break, drop a Smoke Bomb at your feet, concealing you from enemies for 3s. Cooldown: 40s.",
    talent:   { type: "fixed", talentId: "smoke-screen" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "Year 6 Season 3 Track / Target Loot / Exotic Caches",
    flavorText: "\"I'd like to make a withdrawal.\"",
  },
  {
    gearId: "overdogs",
    gearName: "Overdogs",
    slot: "gloves",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Amplifies Weapon Damage by 30% to the lowest ranking enemies currently in combat, as per the Tier hierarchy. Tier 1: Hunter, Rogue, Leader, Tank, Shield, Heavy Weapons, RPG, Medic, Controller, Warhound, Marauder. Tier 2: Support, Engineer, Bodyguard, Immobilizer, Bomber, Mini Tank, Drone Operator. Tier 3: Any other enemy or skill proxy. (Tier 3 is lowest, Tier 1 is highest.)",
    talent:   { type: "fixed", talentId: "weakest-link" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "Year 7 Season 2 Track",
    flavorText: "\"Start from the bottom and make your way up.\"",
  },
  {
    gearId: "rugged-gauntlets",
    gearName: "Rugged Gauntlets",
    slot: "gloves",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "-50% Recoil Penalty when hip-firing. -50% Recoil Penalty when blind-firing from cover.",
    talent:   { type: "fixed", talentId: "iron-grip" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "Year 5 Season 3 Track (TU20) / Target Loot / Exotic Caches",
    flavorText: "\"Can't say I invented this, but at least I had a hand in it.\" - Calvin McManus",
  },

  // ── Holsters ───────────────────────────────────────────────────────────────

  {
    gearId: "forge",
    gearName: "Forge",
    slot: "holster",
    brand: "Richter & Kaiser GmbH",
    rarity: "Named",
    namedPerkDesc: "Shield Health",
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Shield Health", value: "50%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"The space in between is where you want to be. Not the hammer. Not the anvil. You are the impact, the energy, the potential. Bend or break, you will find purpose. And in purpose, there is truth.\"",
  },
  {
    gearId: "ammo-dump",
    gearName: "Ammo Dump",
    slot: "holster",
    brand: "Badger Tuff",
    rarity: "Named",
    namedPerkDesc: "Ammo Capacity",
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Ammo Capacity", value: "10%" },
      { type: "any-basic" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "Crafted",
    flavorText: "\"Whaddya mean yer outta ammo? Dig around in that mess you call a holster and find something to shove in your gun and shoot!\" - True Sons platoon leader",
  },
  {
    gearId: "picaros-holster",
    gearName: "Picaros Holster",
    slot: "holster",
    brand: "Brazos de Arcabuz",
    rarity: "Named",
    namedPerkDesc: "Weapon Damage Minor Stat",
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Weapon Damage", value: "10%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
  },
  {
    gearId: "spot-on",
    gearName: "Spot-On",
    slot: "holster",
    brand: "Urban Lookout",
    rarity: "Named",
    namedPerkDesc: "Accuracy",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Accuracy", value: "38%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"It's all in the hip.\"",
  },
  {
    gearId: "salvo",
    gearName: "Salvo",
    slot: "holster",
    brand: "Unit Alloys",
    rarity: "Named",
    namedPerkDesc: "Rate of Fire",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Rate of Fire", value: "5%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
  },
  {
    gearId: "claws-out",
    gearName: "Claws Out",
    slot: "holster",
    brand: "Wyvern Wear",
    rarity: "Named",
    namedPerkDesc: "Melee Damage + Pistol Damage",
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Melee Damage", value: "500%" },
      { type: "any-basic" },
      { type: "fixed", name: "Pistol Damage", value: "11%" },
    ],
    modSlots: 0,
    source: "DZ",
    flavorText: "\"Rip and tear!\"",
  },

  // ── Exotic Holsters ────────────────────────────────────────────────────────

  {
    gearId: "centurion-scabbard",
    gearName: "Centurion Scabbard",
    slot: "holster",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Swapping weapons will give the following groups of bonuses one by one, in order: 1. +20% Rate of Fire, +20% Weapon Damage. 2. +50% Magazine Size, +50% Reload Speed. The bonuses remain active for 12s or until the next weapon swap. Swapping to your sidearm will not trigger the next group of bonuses.",
    talent:   { type: "fixed", talentId: "counter" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Weapon Handling",     value: "7% – 8%"    },
    ],
    modSlots: 0,
    source: "Year 6 Season 2 Track / Target Loot / Exotic Caches",
    flavorText: "\"It's better to have more than one gun in your holster.\"",
  },
  {
    gearId: "dodge-city-gunslingers-holster",
    gearName: "Dodge City Gunslinger's Holster",
    slot: "holster",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "While your pistol is holstered, gain a stacking buff every 0.3s, up to 100. When you swap to it, your first shot consumes the buff and deals +10% damage per stack. This deals headshot damage to anywhere you hit. Requires Pistol Equipped.",
    talent:   { type: "fixed", talentId: "quick-draw" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Weapon Handling",  value: "7% – 8%"    },
      { type: "fixed", name: "Headshot Damage",  value: "1.3% – 10%" },
    ],
    modSlots: 0,
    source: "Project Questline (blueprint vendor) / Target Loot / Exotic Caches",
    flavorText: "\"Fast is fine, but accuracy is everything. In a gunfight... You need to take your time in a hurry.\" - Wyatt Earp",
  },
  {
    gearId: "imperial-dynasty",
    gearName: "Imperial Dynasty",
    slot: "holster",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "While in combat, applies burn to the enemy closest to you within 20m. Cooldown: 35s.",
    talent:   { type: "fixed", talentId: "dragons-glare" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Status Effects",    value: "5% – 10%" },
      { type: "fixed", name: "Hazard Protection", value: "5% – 10%" },
    ],
    modSlots: 0,
    source: "Cleaners Bosses / Target Loot / Exotic Caches",
    flavorText: "\"Symbols are important. Look at the phoenix you wear on your sleeve. The dragon bears a similar significance to me.\" - Faye Lau",
  },
  {
    gearId: "shocker-punch",
    gearName: "Shocker Punch",
    slot: "holster",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "While Shocker Punch is equipped, the stun received from the Shock status effect is reduced by 50%. Using a shield gives 100% bonus melee damage. Using St. Elmo's Engine with this holster gives 100% extra melee damage and makes the next melee attack apply shock to the target. Using all three items provides all bonuses and the Shock from melee attacks has a 5m radius from the first target. 15 second cooldown.",
    talent:   { type: "fixed", talentId: "defibrillator" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Explosive Resistance", value: "1% – 10%"  },
      { type: "fixed", name: "Hazard Protection",    value: "5% – 10%"  },
    ],
    modSlots: 0,
    source: "Year 5 Season 1 (TU18) / Target Loot / Exotic Caches",
    flavorText: "\"After getting sucker punched at the mall, I came up with a shocking solution.\" Anonymous",
  },
  {
    gearId: "waveform",
    gearName: "Waveform",
    slot: "holster",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Generate a stack of 3% skill damage on one of your skills every second, capping at 10 stacks. After 10 seconds at the cap the stacks transfer to your other skill. The process then repeats ad-infinitum.",
    talent:   { type: "fixed", talentId: "alternating-current" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Skill Damage", value: "1.3% – 10%" },
      { type: "fixed", name: "Skill Haste",  value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "Season 4 Track / Target Loot / Exotic Caches",
    flavorText: "Graphite layers are suffused throughout the holster kevlar weave, that when the wearer moves creates an inductive oscillating electromagnetic field. This field allows for remote charging of electrical devices.",
  },
  {
    gearId: "nimble-holster",
    gearName: "Nimble Holster",
    slot: "holster",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Receive repairs of 5% of your Total Armor for every 1m run in cover-to-cover. Damage taken while doing a cover-to-cover is healed over 10s.",
    talent:   { type: "fixed", talentId: "bob-and-weave" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "Year 7 Season 1 Track / Target Loot / Exotic Caches",
    flavorText: "\"Run for your life.\"",
  },

  // ── Exotic Kneepads ────────────────────────────────────────────────────────

  {
    gearId: "sawyers-kneepads",
    gearName: "Sawyer's Kneepads",
    slot: "kneepads",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Cannot be staggered by explosions. Increases total weapon damage by 3% each second you are not moving. Stacks up to 10 until you start moving. All stacks lost 10s after moving.",
    talent:   { type: "fixed", talentId: "stand-your-ground" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "fixed", name: "Explosive Resistance", value: "1% – 10%"    },
      { type: "fixed", name: "Health",               value: "8405 – 18935" },
    ],
    modSlots: 0,
    source: "Hyena Bosses / Target Loot / Exotic Caches",
    flavorText: "\"When I lost my leg, I thought that was it for me. But I found new purpose. I rose, just like the phoenix on my patch. Now it's time for these to find new purpose.\" - Odessa Sawyer",
  },
  {
    gearId: "acosta-kneepads",
    gearName: "Acosta Kneepads",
    slot: "kneepads",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Vaulting grants +10% Movement Speed for 3s. After not moving for 5s, receive +20% Movement Speed for 5s. Being applied a Status Effect grants +10% Movement Speed for 5s. Max Movement Speed bonus is 20%. The bonuses do not stack with Movement Speed bonuses from other sources. -50% Movement Impairment penalty from Status Effects.",
    talent:   { type: "fixed", talentId: "escape-plan" },
    cores:    [{ type: "fixed", name: "Armor" }],
    minors:   [
      { type: "any-basic-group", group: "offensive" },
      { type: "any-basic-group", group: "defensive" },
    ],
    modSlots: 0,
    source: "Year 6 Season 1 Track / Target Loot / Exotic Caches",
    flavorText: "\"They got the asses caught by the JTF, but they don't have my mad parkour skills.\" - Eva Acosta",
  },
  {
    gearId: "blacklisters",
    gearName: "Blacklisters",
    slot: "kneepads",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Shooting an enemy applies a mark. Only one mark can be active at a time. The mark disappears after 15s, or when the marked enemy dies. Receive 600% Amplified Damage from the marked enemy. Deal 20% Amplified Damage to unmarked enemies. If only one enemy remains in combat, the mark disappears and cannot be reapplied.",
    talent:   { type: "fixed", talentId: "ostracize" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "Y7S2 Climax Mission (Master guaranteed / any difficulty drop)",
    flavorText: "\"Screw that one guy in particular.\"",
  },
  {
    gearId: "ninjabike-messenger-kneepads",
    gearName: "NinjaBike Messenger Kneepads",
    slot: "kneepads",
    brand: "",
    rarity: "Exotic",
    namedPerkDesc: "Performing a cover to cover or vaulting reloads your drawn weapon and grants +25% bonus armor for 5s.",
    talent:   { type: "fixed", talentId: "parkour" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Chance", value: "1.2% – 6%"  },
      { type: "fixed", name: "Critical Hit Damage", value: "6% – 12%"   },
    ],
    modSlots: 0,
    source: "DZ Airdrops (3%) / Target Loot / Exotic Caches",
    flavorText: "\"Parkour! Parkour!\" - an over-enthusiastic NinjaBike messenger",
  },

  // ── Kneepads ───────────────────────────────────────────────────────────────

  {
    gearId: "foxs-prayer",
    gearName: "Fox's Prayer",
    slot: "kneepads",
    brand: "Overlord Armaments",
    rarity: "Named",
    namedPerkDesc: "Damage to Targets Out of Cover",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Damage to Targets Out of Cover", value: "8%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"Ever heard of an atheist in a foxhole? Me neither.\"",
  },
  {
    gearId: "snow-machine",
    gearName: "Snow Machine",
    slot: "kneepads",
    brand: "Electrique",
    rarity: "Named",
    namedPerkDesc: "Status effects apply snowfall to target.",
    talent:   { type: "fixed", talentId: "flurry" },
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [{ type: "any-basic" }, { type: "any-basic" }, { type: "any-basic" }],
    modSlots: 0,
    source: "Special Event Hoarder",
    flavorText: "\"Like our friends down under, if we want snow on Christmas we have to make it ourselves\"",
  },
  {
    gearId: "turmoil",
    gearName: "Turmoil",
    slot: "kneepads",
    brand: "Česká Výroba s.r.o.",
    rarity: "Named",
    namedPerkDesc: "When dealing Weapon Damage to an enemy, 50% of the damage will be dealt to another enemy within 30m instead. When there are no enemies nearby, deal damage normally. Does not apply to Armor Plates.",
    talent:   { type: "fixed", talentId: "bewildered" },
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Critical Hit Damage", value: "12%" },
      { type: "fixed", name: "Critical Hit Chance", value: "6%" },
    ],
    modSlots: 0,
    source: "Limited Time April Fools Event",
    flavorText: "Never let them know your next move.",
  },
  {
    gearId: "emperors-guard",
    gearName: "Emperor's Guard",
    slot: "kneepads",
    brand: "Murakami Industries",
    rarity: "Named",
    namedPerkDesc: "% Armor Regeneration",
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Armor Regeneration", value: "1%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "DZ",
    flavorText: "\"Fall down seven times, get up eight.\"",
  },
  {
    gearId: "grease",
    gearName: "Grease",
    slot: "kneepads",
    brand: "Shiny Monkey Gear",
    rarity: "Named",
    namedPerkDesc: "Extra Status Effects",
    cores:    [{ type: "fixed", name: "Skill Tier" }],
    minors:   [
      { type: "fixed", name: "Status Effects", value: "16%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"I'm not in danger, you're in danger\"",
  },
  {
    gearId: "cloak",
    gearName: "Cloak",
    slot: "kneepads",
    brand: "Imminence Armaments",
    rarity: "Named",
    namedPerkDesc: "% Reduced Threat",
    cores:    [{ type: "fixed", name: "Weapon Damage" }],
    minors:   [
      { type: "fixed", name: "Reduced Threat", value: "50%" },
      { type: "any-basic" },
    ],
    modSlots: 0,
    source: "LZ",
    flavorText: "\"No sudden movements.\"",
  },

];

// ─────────────────────────────────────────────────────────────────────────────
// Derived helpers
// ─────────────────────────────────────────────────────────────────────────────

export const NAMED_GEAR_MAP = new Map(NAMED_GEAR.map(g => [g.gearId, g]));

export const namedGearForSlot = (slot: GearSlot): NamedGearItem[] =>
  NAMED_GEAR.filter(g => g.slot === slot);
